package com.hequalab.rai.domain.servizi.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultAggregateDeleted;
import com.hequalab.rai.domain.servizi.ServiziId;

public class ServiziDeleted extends DefaultAggregateDeleted<ServiziId> {

	private static final long serialVersionUID = 1L;

	
	@SuppressWarnings("unused")
	private ServiziDeleted() {
	}

	public ServiziDeleted(ServiziId id) {
		super(id);
	}				

}