package com.hequalab.rai.domain.servizi.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultEvent;
import com.hequalab.rai.domain.servizi.ServiziId;

public class ServiziUpdated extends DefaultEvent<ServiziId> {

	private static final long serialVersionUID = 1L;
	
	private String descrizione;
	private String lotto;
	private Double importo;
	private String note;
	private String tipologia;
	private String codice;
	private String tipo;
	
	@SuppressWarnings("unused")
	private ServiziUpdated() {
	}

	public ServiziUpdated(ServiziId id, String descrizione, String lotto, Double importo, String note, String tipologia, String codice, String tipo) {
		super(id);
		this.setDescrizione(descrizione);
		this.setlotto(lotto);
		this.setImporto(importo);
		this.setNote(note);
		this.setTipologia(tipologia);
		this.setCodice(codice);
		this.setTipo(tipo);
	}

	public String getDescrizione() {
		return descrizione;
	}
	
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}
	
	public String getlotto() {
		return lotto;
	}
	
	public void setlotto(String lotto) {
		this.lotto = lotto;
	}
	
	public Double getImporto() {
		return importo;
	}
	
	public void setImporto(Double importo) {
		this.importo = importo;
	}
	
	public String getNote() {
		return note;
	}
	
	public void setNote(String note) {
		this.note = note;
	}
	
	public String getTipologia() {
		return tipologia;
	}
	
	public void setTipologia(String tipologia) {
		this.tipologia = tipologia;
	}
	
	public String getCodice() {
		return codice;
	}
	
	public void setCodice(String codice) {
		this.codice = codice;
	}
	
	public String getTipo() {
		return tipo;
	}
	
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}
	
	
}