package com.hequalab.rai.api.read.types;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.domain.filiali.FilialiId;

public class FilialiIdType extends UUIDIdentityType<FilialiId> {

	public FilialiIdType() {
		super(FilialiId.class);
	}

}