package com.hequalab.rai.api.read.types;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.domain.fornitori.FornitoriId;

public class FornitoriIdType extends UUIDIdentityType<FornitoriId> {

	public FornitoriIdType() {
		super(FornitoriId.class);
	}

}