package com.hequalab.rai.api.read.types;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.domain.lotti.LottiId;

public class LottiIdType extends UUIDIdentityType<LottiId> {

	public LottiIdType() {
		super(LottiId.class);
	}

}