package com.hequalab.rai.api.read.types;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.domain.luoghi.LuoghiId;

public class LuoghiIdType extends UUIDIdentityType<LuoghiId> {

	public LuoghiIdType() {
		super(LuoghiId.class);
	}

}