package com.hequalab.rai.api.read.types;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.domain.richiestanuovoservizio.RichiestaNuovoServizioId;

public class RichiestaNuovoServizioIdType extends UUIDIdentityType<RichiestaNuovoServizioId> {

	public RichiestaNuovoServizioIdType() {
		super(RichiestaNuovoServizioId.class);
	}

}