package com.hequalab.rai.api.read.types;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.domain.servizi.ServiziId;

public class ServiziIdType extends UUIDIdentityType<ServiziId> {

	public ServiziIdType() {
		super(ServiziId.class);
	}

}