package com.hequalab.rai.domain.filiali;

/*
 * Class generated by AppWizard
 */
 
import com.hequalab.rai.dddd.UUIDIdentity;

public class FilialiId extends UUIDIdentity {
	
	private static final long serialVersionUID = 1L;
	
	public FilialiId() {
		super();
	}

	public FilialiId(String uuid) {
		super(uuid);
	}

}