package com.hequalab.rai.api.read.views.lotti;

/*
 * Class generated by AppWizard
 */

import java.util.Set;

import com.google.common.collect.Sets;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Type;

import com.hequalab.rai.api.read.views.BaseEntity;

import javax.persistence.JoinTable;

import com.hequalab.rai.domain.lotti.LottiId;



@SuppressWarnings("unused")
@Entity
@Table(name = "lotti_view")
public class LottiView extends BaseEntity {

	private static final long serialVersionUID = 1L;

    	@Type(type = "LottiIdType")
    	private LottiId lottiId;
	
	private String descrizione;
	private String divisione;
	
	
	public LottiId getLottiId() {
		return lottiId;
	}

	public void setLottiId(LottiId lottiId) {
		this.lottiId = lottiId;
	}

	public String getDescrizione() {
		return descrizione;
	}
	
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getDivisione() {
		return divisione;
	}

	public void setDivisione(String divisione) {
		this.divisione = divisione;
	}

}