package com.hequalab.rai.api.read.views.lotti;

/*
 * Class generated by AppWizard
 */

import org.hibernate.SessionFactory;
import com.hequalab.rai.api.read.views.AbstractViewWriter;
import com.hequalab.rai.api.write.ApiContext;
import com.hequalab.rai.dddd.EventListener;
import com.hequalab.rai.dddd.EventStream;
import com.hequalab.rai.domain.lotti.events.LottiCreated;
import com.hequalab.rai.domain.lotti.events.LottiDeleted;
import com.hequalab.rai.domain.lotti.events.LottiUpdated;



public class LottiViewWriter extends AbstractViewWriter<LottiView> {

	public LottiViewWriter(SessionFactory sessionFactory) {
		super(sessionFactory, LottiView.class, "lottiId");
	}

	@EventListener
	public void apply(LottiCreated event, EventStream<ApiContext> stream) {
		LottiView u = new LottiView();
		u.setLottiId(event.getId());
		u.setDescrizione(event.getDescrizione());
		u.setDivisione(event.getDivisione());
		session().save(u);
	}

	@EventListener
	public void apply(LottiUpdated event, EventStream<ApiContext> stream) {
		LottiView u = find(event.getId());
		u.setDescrizione(event.getDescrizione());
		u.setDivisione(event.getDivisione());
		session().update(u);
	}

	@EventListener
	public void apply(LottiDeleted event, EventStream<ApiContext> stream) {
		session().delete(find(event.getId()));
	}

}