/*
 * File: app/store/storeUtenti.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.store.storeUtenti', {
    extend: 'Ext.data.Store',

    requires: [
        'Rai.model.utenti',
        'Ext.data.proxy.Rest',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            pageSize: 300,
            remoteFilter: true,
            storeId: 'storeUtenti',
            autoLoad: false,
            model: 'Rai.model.utenti',
            proxy: {
                type: 'rest',
                idParam: 'userId',
                url: '/users',
                reader: {
                    type: 'json',
                    rootProperty: 'items'
                },
                writer: {
                    type: 'json',
                    writeRecordId: false
                }
            }
        }, cfg)]);
    }
});