package com.hequalab.rai.api.read.views.produzioni;

/*
 * Class generated by AppWizard
 */

import java.util.Set;

import com.google.common.collect.Sets;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Type;

import com.hequalab.rai.api.read.views.BaseEntity;

import javax.persistence.JoinTable;

import com.hequalab.rai.domain.produzioni.ProduzioniId;



@SuppressWarnings("unused")
@Entity
@Table(name = "produzioni_view")
public class ProduzioniView extends BaseEntity {

	private static final long serialVersionUID = 1L;

	@Type(type = "ProduzioniIdType")
	private ProduzioniId produzioniId;
	
	private String descrizione;
	private String divisione;
	private String matricola;
	
	public ProduzioniId getProduzioniId() {
		return produzioniId;
	}

	public void setProduzioniId(ProduzioniId produzioniId) {
		this.produzioniId = produzioniId;
	}

	public String getDescrizione() {
		return descrizione;
	}
	
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getDivisione() {
		return divisione;
	}

	public void setDivisione(String divisione) {
		this.divisione = divisione;
	}

	public String getMatricola() {
	    return matricola;
	}

	public void setMatricola(String matricola) {
	    this.matricola = matricola;
	}

}