/*
 * File: app/model/richiestaServizio.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.model.richiestaServizio', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    idProperty: 'richiestaNuovoServizioId',

    fields: [
        {
            name: 'richiestaNuovoServizioId'
        },
        {
            type: 'string',
            name: 'nome'
        },
        {
            type: 'string',
            name: 'note'
        },
        {
            type: 'date',
            name: 'data'
        },
        {
            type: 'date',
            name: 'timeStamp'
        },
        {
            type: 'date',
            name: 'dataFine'
        },
        {
            name: 'ora'
        },
        {
            type: 'string',
            name: 'ore'
        },
        {
            name: 'uorg'
        },
        {
            name: 'tipologia'
        },
        {
            name: 'lotto'
        },
        {
            name: 'produzione'
        },
        {
            name: 'luogo'
        },
        {
            type: 'float',
            name: 'importo'
        },
        {
            type: 'float',
            convert: function(v, rec) {
                var fineData = null;
                var storeFilters = Ext.StoreManager.lookup('storeRichiesteServizi').getFilters();
                for (var i = 0; i < storeFilters.items.length; i++){
                    if( storeFilters.items[i]._id === 'fineData'){
                        fineData = storeFilters.items[i]._value;
                        break;
                    }
                }

                console.log('fineData: ' + fineData);

                if (fineData === null)return v;
                return v;

            },
            name: 'costoTotale'
        },
        {
            name: 'matricola'
        },
        {
            type: 'string',
            name: 'fornitore'
        },
        {
            type: 'string',
            name: 'divisione'
        },
        {
            type: 'string',
            name: 'stato'
        }
    ]
});