package com.hequalab.rai.api.read.views.filiali;

/*
 * Class generated by AppWizard
 */

import java.util.Set;
import com.google.common.collect.Sets;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Type;
import com.hequalab.rai.api.read.views.BaseEntity;
import javax.persistence.JoinTable;
import com.hequalab.rai.domain.filiali.FilialiId;



@SuppressWarnings("unused")
@Entity
@Table(name = "filiali_view")
public class FilialiView extends BaseEntity {

	private static final long serialVersionUID = 1L;

	@Type(type = "FilialiIdType")
	private FilialiId filialiId;
	
	private String nome;
	
	
	public FilialiId getFilialiId() {
		return filialiId;
	}

	public void setFilialiId(FilialiId filialiId) {
		this.filialiId = filialiId;
	}

	public String getNome() {
		return nome;
	}
	
	public void setNome(String nome) {
		this.nome = nome;
	}

}