package com.hequalab.rai.api.read.views.filiali;

/*
 * Class generated by AppWizard
 */

import org.hibernate.SessionFactory;
import com.hequalab.rai.api.read.views.AbstractViewWriter;
import com.hequalab.rai.api.write.ApiContext;
import com.hequalab.rai.dddd.EventListener;
import com.hequalab.rai.dddd.EventStream;
import com.hequalab.rai.domain.filiali.events.FilialiCreated;
import com.hequalab.rai.domain.filiali.events.FilialiDeleted;
import com.hequalab.rai.domain.filiali.events.FilialiUpdated;



public class FilialiViewWriter extends AbstractViewWriter<FilialiView> {

	public FilialiViewWriter(SessionFactory sessionFactory) {
		super(sessionFactory, FilialiView.class, "filialiId");
	}

	@EventListener
	public void apply(FilialiCreated event, EventStream<ApiContext> stream) {
		FilialiView u = new FilialiView();
		u.setFilialiId(event.getId());
		u.setNome(event.getNome());
		session().save(u);
	}

	@EventListener
	public void apply(FilialiUpdated event, EventStream<ApiContext> stream) {
		FilialiView u = find(event.getId());
		u.setNome(event.getNome());
		session().update(u);
	}

	@EventListener
	public void apply(FilialiDeleted event, EventStream<ApiContext> stream) {
		session().delete(find(event.getId()));
	}

}