package com.hequalab.rai.domain.fornitori.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultAggregateDeleted;
import com.hequalab.rai.domain.fornitori.FornitoriId;

public class FornitoriDeleted extends DefaultAggregateDeleted<FornitoriId> {

	private static final long serialVersionUID = 1L;

	
	@SuppressWarnings("unused")
	private FornitoriDeleted() {
	}

	public FornitoriDeleted(FornitoriId id) {
		super(id);
	}				

}