package com.hequalab.rai.domain.fornitori.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultEvent;
import com.hequalab.rai.domain.fornitori.FornitoriId;

public class FornitoriCreated extends DefaultEvent<FornitoriId> {

	private static final long serialVersionUID = 1L;
	
	private String note;
	private String ragioneSociale;
	
	@SuppressWarnings("unused")
	private FornitoriCreated() {
	}

	public FornitoriCreated(FornitoriId id ,String note,String ragioneSociale) {
		super(id);
		this.setNote(note);
		this.setRagioneSociale(ragioneSociale);
	}

	public String getNote() {
		return note;
	}
	
	public void setNote(String note) {
		this.note = note;
	}
	public String getRagioneSociale() {
		return ragioneSociale;
	}
	
	public void setRagioneSociale(String ragioneSociale) {
		this.ragioneSociale = ragioneSociale;
	}
	
}
