package com.hequalab.rai.domain.servizi;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.domain.servizi.events.ServiziCreated;
import com.hequalab.rai.domain.servizi.events.ServiziDeleted;
import com.hequalab.rai.domain.servizi.events.ServiziUpdated;
import com.hequalab.rai.dddd.DeletableAggregate;

public class Servizi extends DeletableAggregate<Servizi,ServiziId,ServiziDeleted> {

	private Servizi(ServiziId id) {
		super(id, ServiziDeleted.class);
	}

	public Servizi(ServiziId id ,String descrizione,String lotto,Double importo,String note,String tipologia,String codice,String tipo) {
		this(id);
		applyChange(new ServiziCreated(id , descrizione, lotto, importo, note, tipologia, codice, tipo));
	}
	
	public Servizi update( String descrizione,String lotto,Double importo,String note,String tipologia,String codice,String tipo) {
		applyChange(new ServiziUpdated(getId() , descrizione, lotto, importo, note, tipologia, codice, tipo));
		return this;
	}

}