package com.hequalab.rai.domain.servizi;

/*
 * Class generated by AppWizard
 */
 
import com.hequalab.rai.dddd.UUIDIdentity;

public class ServiziId extends UUIDIdentity {
	
	private static final long serialVersionUID = 1L;
	
	public ServiziId() {
		super();
	}

	public ServiziId(String uuid) {
		super(uuid);
	}

}