package com.hequalab.rai.api.dtos.servizi;

/*
 * Class generated by AppWizard
 */
 



public class ServiziCreate {

	private String descrizione;
	private String lotto;
	private Double importo;
	private String note;
	private String tipologia;
	private String codice;
	private String tipo;

    private ServiziCreate() {
    }


	public String getDescrizione() {
		return descrizione;
	}
	
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}


	public String getlotto() {
		return lotto;
	}
	
	public void setlotto(String lotto) {
		this.lotto = lotto;
	}


	public Double getImporto() {
		return importo;
	}
	
	public void setImporto(Double importo) {
		this.importo = importo;
	}


	public String getNote() {
		return note;
	}
	
	public void setNote(String note) {
		this.note = note;
	}


	public String getTipologia() {
		return tipologia;
	}
	
	public void setTipologia(String tipologia) {
		this.tipologia = tipologia;
	}


	public String getCodice() {
		return codice;
	}
	
	public void setCodice(String codice) {
		this.codice = codice;
	}


	public String getTipo() {
		return tipo;
	}
	
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	
}