package com.hequalab.rai.api.read.views.servizi;

/*
 * Class generated by AppWizard
 */

import java.util.Set;
import com.google.common.collect.Sets;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Type;
import com.hequalab.rai.api.read.views.BaseEntity;
import javax.persistence.JoinTable;
import javax.persistence.Lob;

import com.hequalab.rai.domain.servizi.ServiziId;



@SuppressWarnings("unused")
@Entity
@Table(name = "servizi_view")
public class ServiziView extends BaseEntity {

	private static final long serialVersionUID = 1L;
	@Type(type = "ServiziIdType")
	private ServiziId serviziId;
	private String descrizione;
	private String lotto;
	private Double importo;
	
	@Lob
	private String note;
	private String tipologia;
	private String codice;
	private String tipo;
	
	
	public ServiziId getServiziId() {
		return serviziId;
	}

	public void setServiziId(ServiziId serviziId) {
		this.serviziId = serviziId;
	}

	public String getDescrizione() {
		return descrizione;
	}
	
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}
	public String getlotto() {
		return lotto;
	}
	
	public void setlotto(String lotto) {
		this.lotto = lotto;
	}
	public Double getImporto() {
		return importo;
	}
	
	public void setImporto(Double importo) {
		this.importo = importo;
	}
	public String getNote() {
		return note;
	}
	
	public void setNote(String note) {
		this.note = note;
	}
	public String getTipologia() {
		return tipologia;
	}
	
	public void setTipologia(String tipologia) {
		this.tipologia = tipologia;
	}
	public String getCodice() {
		return codice;
	}
	
	public void setCodice(String codice) {
		this.codice = codice;
	}
	public String getTipo() {
		return tipo;
	}
	
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}