package com.hequalab.rai.domain.richiestanuovoservizio;

/*
 * Class generated by AppWizard
 */
 
import com.hequalab.rai.dddd.UUIDIdentity;

public class RichiestaNuovoServizioId extends UUIDIdentity {
	
	private static final long serialVersionUID = 1L;
	
	public RichiestaNuovoServizioId() {
		super();
	}

	public RichiestaNuovoServizioId(String uuid) {
		super(uuid);
	}

}