package com.hequalab.rai.domain.produzioni;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.domain.produzioni.events.ProduzioniCreated;
import com.hequalab.rai.domain.produzioni.events.ProduzioniDeleted;
import com.hequalab.rai.domain.produzioni.events.ProduzioniUpdated;
import com.hequalab.rai.dddd.DeletableAggregate;


public class Produzioni extends DeletableAggregate<Produzioni,ProduzioniId,ProduzioniDeleted> {

	private Produzioni(ProduzioniId id) {
		super(id, ProduzioniDeleted.class);
	}

	public Produzioni(ProduzioniId id ,String descrizione,String divisione,String matricola) {
		this(id);
		applyChange(new ProduzioniCreated(id , descrizione,divisione, matricola));
	}
	
	public Produzioni update( String descrizione,String divisione,String matricola) {
		applyChange(new ProduzioniUpdated(getId() , descrizione,divisione,matricola));
		return this;
	}

}