package com.hequalab.rai.domain.produzioni;

/*
 * Class generated by AppWizard
 */
 
import com.hequalab.rai.dddd.UUIDIdentity;

public class ProduzioniId extends UUIDIdentity {
	
	private static final long serialVersionUID = 1L;
	
	public ProduzioniId() {
		super();
	}

	public ProduzioniId(String uuid) {
		super(uuid);
	}

}