package com.hequalab.rai.api.dtos.luoghi;

/*
 * Class generated by AppWizard
 */
 



public class LuoghiCreate {

	private String indirizzo;
	private String descrizione;
	private String cap;
	private String divisione;

    private LuoghiCreate() {
    }


	public String getIndirizzo() {
		return indirizzo;
	}
	
	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}


	public String getDescrizione() {
		return descrizione;
	}
	
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}


	public String getCap() {
		return cap;
	}
	
	public void setCap(String cap) {
		this.cap = cap;
	}


	public String getDivisione() {
		return divisione;
	}


	public void setDivisione(String divisione) {
		this.divisione = divisione;
	}

	
}