package com.hequalab.rai.api.read.views.luoghi;

/*
 * Class generated by AppWizard
 */

import org.hibernate.SessionFactory;
import com.hequalab.rai.api.read.views.AbstractViewWriter;
import com.hequalab.rai.api.write.ApiContext;
import com.hequalab.rai.dddd.EventListener;
import com.hequalab.rai.dddd.EventStream;
import com.hequalab.rai.domain.luoghi.events.LuoghiCreated;
import com.hequalab.rai.domain.luoghi.events.LuoghiDeleted;
import com.hequalab.rai.domain.luoghi.events.LuoghiUpdated;



public class LuoghiViewWriter extends AbstractViewWriter<LuoghiView> {

	public LuoghiViewWriter(SessionFactory sessionFactory) {
		super(sessionFactory, LuoghiView.class, "luoghiId");
	}

	@EventListener
	public void apply(LuoghiCreated event, EventStream<ApiContext> stream) {
		LuoghiView u = new LuoghiView();
		u.setLuoghiId(event.getId());
		u.setIndirizzo(event.getIndirizzo());
		u.setDescrizione(event.getDescrizione());
		u.setCap(event.getCap());
		u.setDivisione(event.getDivisione());
		session().save(u);
	}

	@EventListener
	public void apply(LuoghiUpdated event, EventStream<ApiContext> stream) {
		LuoghiView u = find(event.getId());
		u.setIndirizzo(event.getIndirizzo());
		u.setDescrizione(event.getDescrizione());
		u.setCap(event.getCap());
		u.setDivisione(event.getDivisione());
		session().update(u);
	}

	@EventListener
	public void apply(LuoghiDeleted event, EventStream<ApiContext> stream) {
		session().delete(find(event.getId()));
	}

}