package com.hequalab.rai.api.read.views.luoghi;

/*
 * Class generated by AppWizard
 */

import java.util.Set;

import com.google.common.collect.Sets;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Type;

import com.hequalab.rai.api.read.views.BaseEntity;

import javax.persistence.JoinTable;

import com.hequalab.rai.domain.luoghi.LuoghiId;

@SuppressWarnings("unused")
@Entity
@Table(name = "luoghi_view")
public class LuoghiView extends BaseEntity {

	private static final long serialVersionUID = 1L;

	@Type(type = "LuoghiIdType")
	private LuoghiId luoghiId;
	private String indirizzo;
	private String descrizione;
	private String cap;
	private String divisione;
	
	public LuoghiId getLuoghiId() {
		return luoghiId;
	}

	public void setLuoghiId(LuoghiId luoghiId) {
		this.luoghiId = luoghiId;
	}

	public String getIndirizzo() {
		return indirizzo;
	}
	
	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}
	public String getDescrizione() {
		return descrizione;
	}
	
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}
	public String getCap() {
		return cap;
	}
	
	public void setCap(String cap) {
		this.cap = cap;
	}

	public String getDivisione() {
		return divisione;
	}

	public void setDivisione(String divisione) {
		this.divisione = divisione;
	}

}