package com.hequalab.rai.domain.filiali.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultAggregateDeleted;
import com.hequalab.rai.domain.filiali.FilialiId;

public class FilialiDeleted extends DefaultAggregateDeleted<FilialiId> {

	private static final long serialVersionUID = 1L;

	
	@SuppressWarnings("unused")
	private FilialiDeleted() {
	}

	public FilialiDeleted(FilialiId id) {
		super(id);
	}				

}