package com.hequalab.rai.domain.lotti.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultAggregateDeleted;
import com.hequalab.rai.domain.lotti.LottiId;

public class LottiDeleted extends DefaultAggregateDeleted<LottiId> {

	private static final long serialVersionUID = 1L;

	
	@SuppressWarnings("unused")
	private LottiDeleted() {
	}

	public LottiDeleted(LottiId id) {
		super(id);
	}				

}