package com.hequalab.rai.domain.lotti.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultEvent;
import com.hequalab.rai.domain.lotti.LottiId;

public class LottiUpdated extends DefaultEvent<LottiId> {

	private static final long serialVersionUID = 1L;
	
	private String descrizione;
	private String divisione;
	
	@SuppressWarnings("unused")
	private LottiUpdated() {
	}

	public LottiUpdated(LottiId id, String descrizione, String divisione) {
		super(id);
		this.setDescrizione(descrizione);
		this.setDivisione(divisione);
	}

	public String getDescrizione() {
		return descrizione;
	}
	
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getDivisione() {
		return divisione;
	}

	public void setDivisione(String divisione) {
		this.divisione = divisione;
	}
	
	
}