package com.hequalab.rai.domain.produzioni.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultAggregateDeleted;
import com.hequalab.rai.domain.produzioni.ProduzioniId;

public class ProduzioniDeleted extends DefaultAggregateDeleted<ProduzioniId> {

	private static final long serialVersionUID = 1L;

	
	@SuppressWarnings("unused")
	private ProduzioniDeleted() {
	}

	public ProduzioniDeleted(ProduzioniId id) {
		super(id);
	}				

}