package com.hequalab.rai.domain.produzioni.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultEvent;
import com.hequalab.rai.domain.produzioni.ProduzioniId;

public class ProduzioniUpdated extends DefaultEvent<ProduzioniId> {

	private static final long serialVersionUID = 1L;

	private String descrizione;
	private String divisione;
	private String matricola;

	@SuppressWarnings("unused")
	private ProduzioniUpdated() {
	}

	public ProduzioniUpdated(ProduzioniId id, String descrizione,
			String divisione,String matricola) {
		super(id);
		this.setDescrizione(descrizione);
		this.setDivisione(divisione);
		this.setMatricola(matricola);
	}

	public String getDescrizione() {
		return descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getDivisione() {
		return divisione;
	}

	public void setDivisione(String divisione) {
		this.divisione = divisione;
	}

	public String getMatricola() {
	    return matricola;
	}

	public void setMatricola(String matricola) {
	    this.matricola = matricola;
	}

}