/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'fornitori',
        'servizi',
        'filiali',
        'richiestaServizio',
        'reports',
        'utenti',
        'lotti',
        'produzioni',
        'luoghi'
    ],
    stores: [
        'storeFornitori',
        'storeServizi',
        'storeFiliali',
        'storeRichiesteServizi',
        'storeReports',
        'storeUtenti',
        'storeProduzioni',
        'storeLuoghi'
    ],
    views: [
        'frmRichiestaNuovoServizio',
        'winNuovaTipologiaServizio',
        'frmServiziGenerali',
        'frmFornitori',
        'frmProfili',
        'frmFiliali',
        'frmServizi',
        'frmMain',
        'frmLogin',
        'frmAdmin',
        'frmProfiliManager',
        'frmOperatore',
        'frmLotti',
        'frmMatricole',
        'frmProduzioni',
        'frmLuoghi',
        'frmRichiestaServizioAdminOld',
        'uploadWin',
        'frmReportManager',
        'frmServiziManager',
        'nuovaProduzione',
        'creaLuogo',
        'frmRichiestaServizioAdmin'
    ],
    name: 'Rai',

    launch: function() {
        Ext.create('Rai.view.frmMain');
    }

});
