package com.hequalab.rai.api.dtos.richiestanuovoservizio;

/*
 * Class generated by AppWizard
 */



import org.joda.time.LocalDate;

public class RichiestaNuovoServizioUpdate {

	private LocalDate data;
	private LocalDate dataFine;
	private String divisione;
	private String fornitore;
	private String nome;
	private String note;
	private String ora;
	private Integer ore;
	private String uorg;
	private String stato;
	private String lotto;
	private String operatore;
	private String tipologia;
	private Integer matricola;
	private String produzione;
	private String luogo;
	private String utenteApprovante;
	private Double importo;
	private Double costoTotale;
	private String statoEsportazione;
	private String voce;
	private String luogoId;

    private RichiestaNuovoServizioUpdate() {
    }


	public LocalDate getData() {
		return data;
	}
	
		public void setData(Long data) {
		this.data = new LocalDate(Long.valueOf(data * 1000));
	}


	public LocalDate getDataFine() {
		return dataFine;
	}
	
		public void setDataFine(Long dataFine) {
		this.dataFine = new LocalDate(Long.valueOf(dataFine * 1000));
	}


	public String getDivisione() {
		return divisione;
	}
	
	public void setDivisione(String divisione) {
		this.divisione = divisione;
	}


	public String getFornitore() {
		return fornitore;
	}
	
	public void setFornitore(String fornitore) {
		this.fornitore = fornitore;
	}


	public String getNome() {
		return nome;
	}
	
	public void setNome(String nome) {
		this.nome = nome;
	}


	public String getNote() {
		return note;
	}
	
	public void setNote(String note) {
		this.note = note;
	}


	public String getOra() {
		return ora;
	}
	
	public void setOra(String ora) {
		this.ora = ora;
	}


	public Integer getOre() {
		return ore;
	}
	
	public void setOre(Integer ore) {
		this.ore = ore;
	}




	public String getStato() {
		return stato;
	}
	
	public void setStato(String stato) {
		this.stato = stato;
	}


	public String getLotto() {
		return lotto;
	}
	
	public void setLotto(String lotto) {
		this.lotto = lotto;
	}


	public String getOperatore() {
		return operatore;
	}
	
	public void setOperatore(String operatore) {
		this.operatore = operatore;
	}


	public String getTipologia() {
		return tipologia;
	}
	
	public void setTipologia(String tipologia) {
		this.tipologia = tipologia;
	}


	public Integer getMatricola() {
		return matricola;
	}
	
	public void setMatricola(Integer matricola) {
		this.matricola = matricola;
	}


	public String getProduzione() {
		return produzione;
	}
	
	public void setProduzione(String produzione) {
		this.produzione = produzione;
	}


	public String getLuogo() {
		return luogo;
	}
	
	public void setLuogo(String luogo) {
		this.luogo = luogo;
	}


	public String getUtenteApprovante() {
	    return utenteApprovante;
	}


	public void setUtenteApprovante(String utenteApprovante) {
	    this.utenteApprovante = utenteApprovante;
	}


	public Double getImporto() {
	    return importo;
	}


	public void setImporto(Double importo) {
	    this.importo = importo;
	}


	public Double getCostoTotale() {
	    return costoTotale;
	}


	public void setCostoTotale(Double costoTotale) {
	    this.costoTotale = costoTotale;
	}


	public String getStatoEsportazione() {
	    return statoEsportazione;
	}


	public void setStatoEsportazione(String statoEsportazione) {
	    this.statoEsportazione = statoEsportazione;
	}


	public String getUorg() {
	    return uorg;
	}


	public void setUorg(String uorg) {
	    this.uorg = uorg;
	}


	public String getVoce() {
	    return voce;
	}


	public void setVoce(String voce) {
	    this.voce = voce;
	}


	public String getLuogoId() {
	    return luogoId;
	}


	public void setLuogoId(String luogoId) {
	    this.luogoId = luogoId;
	}

	
}