/*
 * File: app/view/frmLoginViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.frmLoginViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.frmlogin',

    onUserNameTxtRender: function(component, eOpts) {
        component.focus();
    },

    onLoginClick: function(button, e, eOpts) {
        var usr = Ext.getCmp("userNameTxt").getValue(),
            pwd = Ext.getCmp("pwdTxt").getValue();

        var saveId = Ext.getCmp('cookieLogin').getValue();

        if (saveId){
            Ext.util.Cookies.set('cookieLogin',"enabled", new Date('5/22/2050 03:05:01 PM GMT-0600'));
        }
        else {
            Ext.util.Cookies.set('cookieLogin',"disabled", new Date('5/22/2050 03:05:01 PM GMT-0600'));
        }

        if (saveId){
            Ext.util.Cookies.set("userNameLogin",usr, new Date('5/22/2050 03:05:01 PM GMT-0600'));
        }

        Ext.Ajax.request({
            url: "../oauth2/token",
            method : "get",
            headers: {
                'Content-Type': 'application/json'
            },
            params : {id:usr,pwd:pwd},
            success : function(response) {

                var tokenAccesso = response.responseText,
                    grado = null;

                ACCESS_TOKEN = tokenAccesso;

                // Prendo le informazioni sull'account
                Ext.Ajax.request({
                    url: '../oauth2/account',
                    headers: {
                        'Authorization': 'Bearer ' + ACCESS_TOKEN,
                    },
                    success: function (response, options) {
                        //alert('response: ' + response.responseText);
                        USER = JSON.parse(response.responseText);
                        USER.roles = JSON.stringify(USER.roles);
                        grado = USER.roles;

                        var stores = Ext.data.StoreManager.map;

                        for (name in stores) {
                            if (name.indexOf('eports') >= 0)continue;
                            if (stores.hasOwnProperty(name)) {
                                store = stores[name];
                                store.clearFilter();
                                store.proxy.headers = {"Authorization":"Bearer " + tokenAccesso};
                                store.autoSync = true;
                                store.autoLoad = true;
                                // store.load();
                            }
                        }

                        if (grado.toLowerCase().indexOf("consorzio") >= 0){
                            Ext.getCmp("pageContainer").removeAll();
                            var panel = Ext.create("Rai.view.frmAdmin");
                            Ext.getCmp("pageContainer").add(panel);
                            panel.show();
                        }
                        else if (grado.toLowerCase().indexOf("manager") >= 0){
                            Ext.getCmp("pageContainer").removeAll();
                            var panel = Ext.create("Rai.view.frmServiziGenerali");
                            Ext.getCmp("pageContainer").add(panel);
                            panel.show();
                        }
                        else if (grado.toLowerCase().indexOf("soperatore") >= 0){

                            Ext.getCmp("pageContainer").removeAll();
                            var panel = Ext.create("Rai.view.frmOperatore");
                            panel.filiale = "Filiale";
                            Ext.getCmp("pageContainer").add(panel);
                            panel.show();
                        }
                        else if (grado.toLowerCase().indexOf("operatore") >= 0){
                            Ext.getCmp("pageContainer").removeAll();
                            var panel = Ext.create("Rai.view.frmOperatore");
                            panel.filiale = "Filiale";
                            Ext.getCmp("pageContainer").add(panel);
                            panel.show();
                        }

                    },
                    failure: function (response, options) {
                        Ext.Msg.show({
                            title:'Errore autenticazione',
                            msg: "Errore durante l'autenticazione: phase 2",
                            buttons: Ext.Msg.Ok,
                        });
                        return;
                    }


                });
            },
            failure : function(response) {
                Ext.Msg.alert("Errore", "Dati di autenticazioni errati.");
            }
        });



    },

    onCookieLoginChange: function(field, newValue, oldValue, eOpts) {

    },

    onFrmLoginAfterRender: function(component, eOpts) {


        Ext.create('Ext.util.KeyMap',"frmLogin",
        {
            key: 13, // this works,
            fn: this.onLoginClick
        }
        );


        if (Ext.util.Cookies.get('cookieLogin') === 'enabled'){
            var username = Ext.util.Cookies.get('userNameLogin');
            Ext.getCmp('userNameTxt').setValue(username);
        }



    }

});
