/*
 * File: app/view/frmProfili.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.frmProfili', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.frmProfili',

    requires: [
        'Rai.view.frmServiziViewModel2',
        'Rai.view.frmServiziViewController2',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.form.field.ComboBox',
        'Ext.grid.filters.filter.String',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.grid.plugin.CellEditing',
        'Ext.grid.filters.Filters',
        'Ext.button.Button'
    ],

    controller: 'frmprofili',
    viewModel: {
        type: 'frmprofili'
    },
    height: 753,
    id: 'frmProfili',
    width: 1099,
    layout: 'border',
    title: 'Area utenti',
    titleAlign: 'center',

    items: [
        {
            xtype: 'panel',
            region: 'center',
            padding: 1,
            layout: 'fit',
            title: '',
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'utentiGrid',
                    title: 'Elenco utenti',
                    store: 'storeUtenti',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'userId',
                            text: 'User ID',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'userName',
                            text: 'Nome account',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'firstName',
                            text: 'Nome',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'lastName',
                            text: 'Cognome',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'email',
                            text: 'eMail',
                            flex: 1.2,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'divisione',
                            text: 'Divisione',
                            flex: 1.2,
                            editor: {
                                xtype: 'combobox',
                                displayField: 'nome',
                                store: 'storeFiliali',
                                valueField: 'nome'
                            },
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'superiore',
                            text: 'Superiore',
                            flex: 1.2,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'roles',
                            text: 'Ruolo',
                            flex: 1.2,
                            editor: {
                                xtype: 'combobox',
                                queryMode: 'local',
                                store: [
                                    'Manager',
                                    'SOperatore',
                                    'Operatore'
                                ]
                            },
                            filter: {
                                type: 'string'
                            }
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'storeUtenti'
                        }
                    ],
                    plugins: [
                        {
                            ptype: 'cellediting'
                        },
                        {
                            ptype: 'gridfilters'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            collapseMode: 'header',
            region: 'west',
            padding: 1,
            width: 328,
            animCollapse: true,
            bodyPadding: 10,
            collapseDirection: 'bottom',
            collapsed: false,
            collapsible: true,
            placeholderCollapseHideMode: 2,
            title: 'Gestisci Utenti',
            titleCollapse: true,
            items: [
                {
                    xtype: 'textfield',
                    id: 'firstName',
                    fieldLabel: 'Nome'
                },
                {
                    xtype: 'textfield',
                    id: 'lastName',
                    fieldLabel: 'Cognome'
                },
                {
                    xtype: 'combobox',
                    id: 'role',
                    fieldLabel: 'Ruolo',
                    queryMode: 'local',
                    store: [
                        'Manager',
                        'SOperatore',
                        'Operatore'
                    ]
                },
                {
                    xtype: 'combobox',
                    id: 'divisione',
                    fieldLabel: 'Filiale',
                    displayField: 'nome',
                    store: 'storeFiliali',
                    valueField: 'nome'
                },
                {
                    xtype: 'textfield',
                    id: 'userName',
                    fieldLabel: 'Utente'
                },
                {
                    xtype: 'textfield',
                    id: 'pwd',
                    fieldLabel: 'Password',
                    inputType: 'password'
                },
                {
                    xtype: 'textfield',
                    id: 'pwdRipetuta',
                    fieldLabel: 'Ripeti password:',
                    inputType: 'password'
                },
                {
                    xtype: 'textfield',
                    id: 'eMail',
                    fieldLabel: 'E-Mail'
                },
                {
                    xtype: 'textfield',
                    id: 'superiore',
                    fieldLabel: 'Superiore'
                },
                {
                    xtype: 'button',
                    text: 'Salva',
                    listeners: {
                        click: 'onAddProfile'
                    }
                },
                {
                    xtype: 'button',
                    text: 'Elimina',
                    listeners: {
                        click: 'onButtonClick'
                    }
                },
                {
                    xtype: 'button',
                    text: 'Annulla'
                }
            ]
        }
    ]

});