/*
 * File: app/view/frmRichiestaNuovoServizio.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.frmRichiestaNuovoServizio', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.frmrichiestanuovoservizio',

    requires: [
        'Rai.view.frmRichiestaNuovoServizioViewModel',
        'Rai.view.frmRichiestaNuovoServizioViewController',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.filters.filter.String',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.filters.filter.Date',
        'Ext.grid.column.Action',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.grid.filters.Filters',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.form.field.TextArea',
        'Ext.panel.Tool'
    ],

    controller: 'frmrichiestanuovoservizio',
    viewModel: {
        type: 'frmrichiestanuovoservizio'
    },
    height: 753,
    id: 'frmrichiestanuovoservizio',
    padding: 0,
    width: 1278,
    title: 'Area servizi',
    titleAlign: 'center',
    defaultListenerScope: true,

    layout: {
        type: 'border',
        padding: 2
    },
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'button',
                    hidden: true,
                    id: 'popButton',
                    text: 'Richiesta nuova tipologia servizio',
                    listeners: {
                        click: {
                            fn: 'onShowWin',
                            scope: 'controller'
                        }
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'panel',
            region: 'center',
            padding: 0,
            layout: 'fit',
            bodyBorder: true,
            bodyPadding: 2,
            title: '',
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'elencoServizi',
                    padding: 5,
                    bodyBorder: true,
                    title: 'Elenco servizi',
                    store: 'storeRichiesteServizi',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'nome',
                            text: 'Servizio',
                            flex: 1,
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'lotto',
                            text: 'Lotto',
                            flex: 1,
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'tipologia',
                            text: 'Tipologia',
                            flex: 1,
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'operatore',
                            text: 'Operatore',
                            flex: 1,
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'produzione',
                            text: 'Produzione',
                            flex: 1,
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'matricola',
                            text: 'Matricola',
                            flex: 0.6,
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'uorg',
                            text: 'Uorg',
                            flex: 0.6,
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'luogo',
                            text: 'Luogo',
                            flex: 1,
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'ore',
                            text: 'Ore',
                            flex: 0.4,
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'data',
                            text: 'Data',
                            flex: 1,
                            format: 'd-m-Y',
                            filter: {
                                type: 'date'
                            }
                        },
                        {
                            xtype: 'datecolumn',
                            dataIndex: 'dataFine',
                            text: 'Data fine',
                            flex: 1,
                            format: 'd-m-Y',
                            filter: {
                                type: 'date'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ora',
                            text: 'Ora',
                            flex: 0.5,
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'stato',
                            text: 'Stato',
                            flex: 0.7,
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'actioncolumn',
                            hidden: true,
                            id: 'approvaSubmit',
                            align: 'center',
                            dataIndex: 'stato',
                            text: 'Approva',
                            flex: 0.8,
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                        Ext.Msg.show({
                                            title:'Richiesta conferma',
                                            msg: 'Stai per approvare la richiesta, vuoi continuare??',
                                            buttons: Ext.Msg.YESNO,
                                            buttonText: {
                                                no:'No',
                                                yes:'Si'
                                            },
                                            fn: function(btn){
                                                if (btn=='yes'){

                                                    if (record.get('stato') === "Approvato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta è stata approvata, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }else if (record.get('stato') === "Non approvato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta non è stata approvata, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }
                                                    else if (record.get('stato') === "Cancellato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta è stata cancellata, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }
                                                    else if (record.get('stato') === "In lavorazione"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta è in lavorazione, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }
                                                    else if (record.get('stato') === "Erogato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "Il servizio è stato erogato, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }

                                                    // record.set('stato',"Approvato");

                                                    Ext.MessageBox.wait('Approvazione della richiesta in corso..');
                                                    Ext.Ajax.request({
                                                        url: '/richiestaNuovoServizio/approvaRichiesta/' + record.get('richiestaNuovoServizioId'),
                                                        headers: {
                                                            'Authorization': 'Bearer ' + ACCESS_TOKEN,
                                                        },
                                                        method:'POST',
                                                        success: function (response, options) {
                                                            Ext.StoreManager.lookup('storeRichiesteServizi').load();
                                                            Ext.MessageBox.updateProgress(1);
                                                            Ext.MessageBox.hide();
                                                            Ext.Msg.show({
                                                                title:'Richiesta approvata',
                                                                msg: "Richiesta approvata con successo.",
                                                                buttons: Ext.Msg.Ok,
                                                            });},
                                                            failure: function (response, options) {
                                                                Ext.MessageBox.updateProgress(1);
                                                                Ext.MessageBox.hide();
                                                                Ext.Msg.show({
                                                                    title:'Errore con il server',
                                                                    msg: "C'è stato un errore durante l'approvazione della richiesta. Errore: " + response.status,
                                                                    buttons: Ext.Msg.Ok,
                                                                });
                                                            }


                                                        });


                                                    }
                                                },
                                                animEl: 'elId'
                                            });






                                    },
                                    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABK0lEQVQ4T6WTzW2DQBBG3zjh7hJcAi1wtTnsVmBSQZwO6CBxB3YDsFJwlFsogRIogWOk/Gy0CNASI4iUPe7M92Z25xvhn0ecfpurZAX7P7CaQhvt8lSu1kabRuJcpdZyEOFpCSBQ3UD5AW8Cm2+IZJepZiUkz9qYJYCr2onDLrftwAJRoU05B5gQu/TjCOCSPmFfaHP0YVNiC+eLNskAuIWqb8/C6aLNXf9Zv9qmF7v4ALAQCjz2lR0kgIc58Qjg/mCXq5OMx9kAaw96DuDwDutXbeorgLuYgLT6vu0uXhfapJOAKYj/5jhTJUI5C/AhvtjdXwHmjLTNVfiiTeWPNM5UZaWdUuvc1srAPSxbGQitJQqEjduDFjAskyVZsrIV6i9I+wkMgCXhXPwH92avn25K/20AAAAASUVORK5CYII=',
                                    tooltip: 'Approva la richiesta'
                                }
                            ]
                        },
                        {
                            xtype: 'actioncolumn',
                            hidden: true,
                            id: 'rifiutaSubmit',
                            align: 'center',
                            dataIndex: 'stato',
                            text: 'Rifiuta',
                            flex: 0.8,
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                        Ext.Msg.show({
                                            title:'Richiesta conferma',
                                            msg: 'Stai per rifiutare la richiesta, vuoi continuare??',
                                            buttons: Ext.Msg.YESNO,
                                            buttonText: {
                                                no:'No',
                                                yes:'Si'
                                            },
                                            fn: function(btn){
                                                if (btn=='yes'){

                                                    if (record.get('stato') === "Approvato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta è stata approvata, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }else if (record.get('stato') === "Non approvato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta non è stata approvata, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }
                                                    else if (record.get('stato') === "Cancellato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta è stata cancellata, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }
                                                    else if (record.get('stato') === "In lavorazione"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta è in lavorazione, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }
                                                    else if (record.get('stato') === "Erogato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "Il servizio è stato erogato, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }


                                                    Ext.MessageBox.wait('Rifiuto della richiesta in corso...');
                                                    Ext.Ajax.request({
                                                        url: '/richiestaNuovoServizio/rifiutaRichiesta/' + record.get('richiestaNuovoServizioId'),
                                                        headers: {
                                                            'Authorization': 'Bearer ' + ACCESS_TOKEN,
                                                        },
                                                        method:'POST',
                                                        success: function (response, options) {
                                                            Ext.StoreManager.lookup('storeRichiesteServizi').load();
                                                            Ext.MessageBox.updateProgress(1);
                                                            Ext.MessageBox.hide();
                                                            Ext.Msg.show({
                                                                title:'Richiesta rifiutata',
                                                                msg: "Richiesta rifiutata con successo.",
                                                                buttons: Ext.Msg.Ok,
                                                            });},
                                                            failure: function (response, options) {
                                                                Ext.MessageBox.updateProgress(1);
                                                                Ext.MessageBox.hide();Ext.Msg.show({
                                                                    title:'Errore con il server',
                                                                    msg: "C'è stato un errore durante il rifiuto della richiesta. Errore: " + response.status,
                                                                    buttons: Ext.Msg.Ok,
                                                                });
                                                            }


                                                        });
                                                    }
                                                },
                                                animEl: 'elId'
                                            });





                                    },
                                    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABZ0lEQVQ4T5VTMVLDMBDcy5Aa+EF4AeYFuGHsjjCDe3hBQufwAOyO5AXQK4Xp4qEg/MC8AJ6Q1GFYRrKVyAqEQZ183t273ZPAO2k/7skeBxCEgAR1mRWIOT9lkhezDxci7iVNorFABj5p606Os2l5Y7+tCdIkqgRybAsElwKpjD4YCGR/Q8QqU+WJvhsCV1kDARnmavbY6u4yKkTk3BGY5Kocipm5i/dGadnBV3inno2yPWkSXwnw4I/GFY6krY7rLWUPTPLJdkJwognM7Lr1XJUHu5SJWiBNokXtCSsZJTEb0GumZuFvbVuwro+SeA7g1Jj4E4E/swveIljHRy6yaXn4F7hJzYxA8K1lIsACkP4mqt2m1iY6MboG+m3r2m1yFpCdF4gYs02M/iLVJCwyVV5sJULer8FgvUgb19urDHLBZpUFDCzQT+zfj0nPrZWtcIvAjNOPe+hS/xDax6XdBjDHSsb+c/4GOP3Lq93zK2QAAAAASUVORK5CYII=',
                                    tooltip: 'Rifiuta la richiesta'
                                }
                            ]
                        },
                        {
                            xtype: 'actioncolumn',
                            id: 'eliminaSubmit',
                            align: 'center',
                            dataIndex: 'stato',
                            text: 'Elimina',
                            flex: 0.8,
                            items: [
                                {
                                    handler: function(view, rowIndex, colIndex, item, e, record, row) {

                                        Ext.Msg.show({
                                            title:'Richiesta conferma',
                                            msg: 'Stai per eliminare la richiesta, vuoi continuare??',
                                            buttons: Ext.Msg.YESNO,
                                            buttonText: {
                                                no:'No',
                                                yes:'Si'
                                            },
                                            fn: function(btn){
                                                if (btn=='yes'){

                                                    if (record.get('stato') === "Approvato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta è stata approvata, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }else if (record.get('stato') === "Non approvato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta non è stata approvata, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }
                                                    else if (record.get('stato') === "Cancellato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta è stata cancellata, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }
                                                    else if (record.get('stato') === "In lavorazione"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "La richiesta è in lavorazione, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }
                                                    else if (record.get('stato') === "Erogato"){
                                                        Ext.Msg.show({
                                                            title:'Operazione non permessa',
                                                            msg: "Il servizio è stato erogato, non sono permesse modifiche",
                                                            buttons: Ext.Msg.Ok,
                                                        });
                                                        return;
                                                    }


                                                    /*
                                                    Possibilità di eliminare la richiesta ad operatore [Il manager devono poter eliminare una richiesta anche approvata
                                                    ma possono farlo al massimo fino a 12 ore prima dall’inizio della richiesta
                                                    */

                                                    Ext.MessageBox.wait('Rimozione della richiesta in corso...');

                                                    Ext.Ajax.request({
                                                        url: '/richiestaNuovoServizio/eliminaRichiesta/' + record.get('richiestaNuovoServizioId'),
                                                        headers: {
                                                            'Authorization': 'Bearer ' + ACCESS_TOKEN,
                                                        },
                                                        method:'POST',
                                                        success: function (response, options) {
                                                            Ext.StoreManager.lookup('storeRichiesteServizi').load();
                                                            Ext.MessageBox.updateProgress(1);
                                                            Ext.MessageBox.hide();

                                                            Ext.Msg.show({
                                                                title:'Richiesta eliminata',
                                                                msg: "Richiesta eliminata",
                                                                buttons: Ext.Msg.Ok,
                                                            });},
                                                            failure: function (response, options) {
                                                                Ext.MessageBox.updateProgress(1);
                                                                Ext.MessageBox.hide();
                                                                Ext.Msg.show({
                                                                    title:'Errore',
                                                                    msg: response.responseText,
                                                                    buttons: Ext.Msg.Ok,
                                                                });
                                                            }


                                                        });


                                                    }
                                                },
                                                animEl: 'elId'
                                            });





                                    },
                                    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAy0lEQVQ4T+2SPQ6CQBCF3ywtxKNoA60KB9Cj4A24gRxFDwBiC40exWDLjpmNaPhxo7Gwcbt5M/vNy8sQRt41CnhMd7OS+vpAkAEDYL1hhZPUpDEDqa0VUEfBjoDV2Oa+xsDey8q1gbfNOgwSgBfvAAAqvLxMOgBjPfRTEKZWCOPs5lXcznQyqEO/IKK5DcDMRy+vHk4HAPksAxIkk14am6wOEqAsaPsvHfwBz5B+FyIRJo5G3CgqAL4fDKWO5kWjkDLjYr2Drw/pU8ANZfC4EZwIficAAAAASUVORK5CYII=',
                                    tooltip: 'Elimina la richiesta'
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'storeRichiesteServizi'
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        if ( Ext.getCmp('elencoServizi').getSelectionModel().getSelection() === undefined || Ext.getCmp('elencoServizi').getSelectionModel().getSelection() === null )return;
                                        var record = Ext.getCmp('elencoServizi').getSelectionModel().getSelection()[0];
                                        Ext.getCmp('lotto').setValue(record.get('lotto'));
                                        Ext.getCmp('comboTipologia').setValue(record.get('tipologia'));
                                        Ext.getCmp('servizioCombo').setValue(record.get('idServizio'));
                                        Ext.getCmp('codiciCombo').setValue(record.get('idServizio'));
                                        Ext.getCmp('produzione').setValue(record.get('idProduzione'));
                                        Ext.getCmp('matricola').setValue(record.get('idProduzione'));
                                        Ext.getCmp('uorg').setValue(record.get('uorg'));
                                        Ext.getCmp('luogo').setValue(record.get('luogoId'));



                                    },
                                    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAqElEQVQ4T+2TwRHCIBREd9OAJWgBcjZHSzEFGK0lFqB24pGzNEA6SAWuE0cdQMcBvcqN+f8/dmEhklXv3BIX7UHO0lq0lzwqNnwBdM4DmH4cfhQl/w6grOF70++A0LNtDevOlSmoA8/fAp4n/gHAeAeL7jwQnGRmoU+eTQ1ID+GQkcYexCoCSBqIams382OmAhQHZ7QZwos929ZEv5S3KBd4tmtzChVcASYkZKSJGNhEAAAAAElFTkSuQmCC',
                                    text: 'Duplica richiesta'
                                }
                            ]
                        }
                    ],
                    plugins: [
                        {
                            ptype: 'gridfilters'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'panel',
                    dock: 'top',
                    height: 160,
                    hidden: true,
                    padding: 1,
                    bodyPadding: 10,
                    collapsible: true,
                    title: 'Filtri',
                    items: [
                        {
                            xtype: 'datefield',
                            fieldLabel: 'Label'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Servizio'
                        },
                        {
                            xtype: 'combobox',
                            fieldLabel: 'Stato'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            padding: 1,
            width: 310,
            bodyPadding: 10,
            collapsible: true,
            title: 'Richiesta nuovo servizio',
            items: [
                {
                    xtype: 'combobox',
                    id: 'lotto',
                    fieldLabel: 'Lotto',
                    displayField: 'descrizione',
                    forceSelection: true,
                    queryMode: 'local',
                    store: [
                        'Lotto 1',
                        'Lotto 2',
                        'Lotto 3',
                        'Lotto 5'
                    ],
                    valueField: 'descrizione',
                    listeners: {
                        change: {
                            fn: 'onLottoChange',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'comboTipologia',
                    fieldLabel: 'Tipologia',
                    value: '',
                    autoSelect: false,
                    displayField: 'descrizione',
                    forceSelection: true,
                    queryMode: 'local',
                    store: [
                        'Canone',
                        'Modulo',
                        'Richiesta',
                        'Trasporto'
                    ],
                    valueField: 'descrizione',
                    listeners: {
                        change: {
                            fn: 'onServizioCombo1Select',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'produzione',
                    fieldLabel: 'Produzione',
                    displayField: 'descrizione',
                    enableRegEx: true,
                    forceSelection: true,
                    store: 'storeProduzioni',
                    valueField: 'produzioniId',
                    listeners: {
                        select: {
                            fn: 'onMatricolaSelect',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'matricola',
                    fieldLabel: 'Matricola',
                    displayField: 'matricola',
                    enableRegEx: true,
                    forceSelection: true,
                    store: 'storeProduzioni',
                    valueField: 'produzioniId',
                    listeners: {
                        select: {
                            fn: 'onMatricolaSelect1',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'servizioCombo',
                    fieldLabel: 'Servizio',
                    displayField: 'descrizione',
                    enableRegEx: true,
                    forceSelection: true,
                    queryMode: 'local',
                    store: 'storeServizi',
                    valueField: 'serviziId',
                    listeners: {
                        select: {
                            fn: 'onServizioComboSelect',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'codiciCombo',
                    fieldLabel: 'Voce',
                    displayField: 'codice',
                    enableRegEx: true,
                    forceSelection: true,
                    queryMode: 'local',
                    store: 'storeServizi',
                    valueField: 'serviziId',
                    listeners: {
                        select: 'onCodiciComboSelect'
                    }
                },
                {
                    xtype: 'combobox',
                    id: 'luogo',
                    fieldLabel: 'Luogo',
                    displayField: 'descrizione',
                    forceSelection: true,
                    store: 'storeLuoghi',
                    valueField: 'luoghiId'
                },
                {
                    xtype: 'textfield',
                    id: 'uorg',
                    fieldLabel: 'Uorg',
                    name: 'uorg'
                },
                {
                    xtype: 'datefield',
                    id: 'dataRichiesta',
                    fieldLabel: 'Data',
                    format: 'd/m/Y',
                    listeners: {
                        select: {
                            fn: 'onDataRichiestaSelect',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'datefield',
                    id: 'dataFine',
                    fieldLabel: 'Data fine',
                    format: 'd/m/Y'
                },
                {
                    xtype: 'timefield',
                    id: 'oraRichiesta',
                    fieldLabel: 'Ora',
                    format: 'H:i'
                },
                {
                    xtype: 'textfield',
                    disabled: true,
                    id: 'oreRichiesta',
                    fieldLabel: 'Ore'
                },
                {
                    xtype: 'textareafield',
                    id: 'noteRichiesta',
                    fieldLabel: 'Note'
                },
                {
                    xtype: 'button',
                    width: 279,
                    text: 'Richiedi Servizio',
                    listeners: {
                        click: {
                            fn: 'onRichiediServizio',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'button',
                    height: 23,
                    padding: '',
                    width: 279,
                    text: 'Annulla',
                    listeners: {
                        click: {
                            fn: 'onClear',
                            scope: 'controller'
                        }
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: {
            fn: 'onFrmrichiestanuovoservizioAfterRender',
            scope: 'controller'
        }
    },
    tools: [
        {
            xtype: 'tool',
            type: 'help',
            listeners: {
                click: {
                    fn: 'onToolClick',
                    scope: 'controller'
                }
            }
        }
    ],

    onCodiciComboSelect: function(combo, record, eOpts) {
        Ext.getCmp('servizioCombo').setValue(record);
    }

});