/*
 * File: app/view/frmServiziGenerali.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.frmServiziGenerali', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.frmservizigenerali',

    requires: [
        'Rai.view.frmFilialeViewViewModel1',
        'Rai.view.frmFilialeViewViewController1',
        'Ext.panel.Panel',
        'Ext.button.Button'
    ],

    controller: 'frmservizigenerali',
    viewModel: {
        type: 'frmservizigenerali'
    },
    layout: 'fit',

    items: [
        {
            xtype: 'panel',
            id: 'frmFiliale_ex',
            layout: 'border',
            title: 'Gestione Lavorazioni - Servizi generali',
            titleAlign: 'center',
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    id: 'mainCont',
                    layout: 'fit',
                    icon: '',
                    iconAlign: 'right',
                    title: ''
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    id: 'frmFiliale_button',
                    width: 150,
                    bodyPadding: 10,
                    collapsible: true,
                    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAADK0lEQVRYR81XXVIaQRjsJhiSkiXkBFlPIJ4g5ATiCWIeXR6EE4gnEB/Ax+AJxBuQE4gncHKCrCypFErxpWbGJcOPuBtJRZ6E+fn+untaIsXHP/vlY3J/BeKLCgpd96jfHlQg+Io7b0vVGSa9lkk3xvv8VtREJttUB2/VTAImuXFNVb1amjtTJ5Dm8iR7X14CfmtYAuUIIiHuvLo7TzNn8BBETx14xzMjaEUNEB8BOXXx4Z9IEa+jE5BFCI9VNd93zy10wG9FXRK7epOAdRXkm/GBrfYgBPjOrAl34st00qRc2d8lVNXCewczDRJHdg2XqupVVifQHnQIfl6aQGugQH5YlQBEvt9UC/40gfawRsiJvU/OVVDYX52Ablnup9nkVq+/m/FAKqD0l9OQJWSynQWGtIeWGaPNzjxFXx4Ik1BnnXsSd8CgOTc8gqAMQoHZetxqo5AyPoHA1wzBKH+cVA2pD7szm0oqEYIbn6ZBWlGTxGFcvQj6qurtGGy0oz6BbWftNFZES+vJBQTFeQnXsampJcLO9EA76hGaz4Y2x6rqNZYFMeujvKEbc8Mf7lgEuFaBV7LAjf7QEPimAq/88HsTkM80FXOj71TqHJC9GO2uPthgcnsTFIr6L1cf5vmu7yd4sVCQGdt9aSkGTNsyr8KZ0dg5d22r5VbIijrweqaas6hMka4WKV09mK3MnDX0BeZV0HQvLaI1GB8D2Kq1x+K8zASs4s22zJqR8QWJktZ7ZLg3HcGDGSFZ1OxAJruXeAR/C0L30XkWCP8nDUnZ5zxwLG3QgSCUzEb5USFyuf6EEBGTLoiiAPvzXiExCK2xGGrTUYZAIZOtzUjxZNwE4UPQw12+kViK09Jw3fsTd2DdgeP7Fi2ZbvWb4SEmDFU1f+oGtgopuxC5XmpIyG1MeDmveL42JALB3eb5k4bEX2XJknhCiFJBYStOXAdPZ8meaUrdR8q+ok4CiUyp9X0NUEKMvNoSW67b2Yuf6Wml1paXAWku2PJc1ISwCLDxpC3/V2Bb22O07gRT03DlP6cyPlSBV0+TZKoEjIeT+/68pFqwWQmXkecnVUF97jfBj0/qfJSTfwAAAABJRU5ErkJggg==',
                    title: 'Menù',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {

                                Ext.getCmp("mainCont").removeAll();
                                var cmp = Ext.create("Rai.view.frmServGenerali");
                                Ext.getCmp("mainCont").add(cmp);
                                cmp.show();
                            },
                            flex: 0,
                            overCls: 'o_button',
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABZElEQVQ4T32TYVEDUQyEdxVAHZwDqAKKAnBAqwBQQFFAq4CrAiqhKKA4wAFFQZjvJu/m3c1c359rX5LN7ibPGp2IWEi6k3Q9Ch0l7Wzz7Y/Lr4i4lPQuaSZpI+kkKTJOHvEnSb+SVraJqwYAmcIfSW8TDJ4lNQDZ7hh2ABGxzk4Uw+LcWSWIbK8LAIVo/0qqf5IuJlCgPpd0sN04IqDUciHpJYu2+X2cAHnNhksA6LxMWjdZcGv7EBH3GSMHj9ANs880eQMA3R+qTjjMXX+S5QnnI4JJYDJnC0AZFRezTNozDdskYzLTaWzDiP99zQDAdjEVSQDgCwVIAKDNfWEXugMA2q5q7edmmL58ZM43AGwY5kAPL1iSXXYeMMk7/GGUyDz2m5hB9gHajBbgwmzOG4gIGu2Zfy9h5HaXkGwAgwHuo72P1Q9qwKCijevoLONEHiu8mHyNIybQp3s3tmTVlhdY5/4DVEimyi/1uJ8AAAAASUVORK5CYII=',
                            text: 'Richieste',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {

                                Ext.getCmp("mainCont").removeAll();
                                var cmp = Ext.create("Rai.view.frmServiziManager");
                                Ext.getCmp("mainCont").add(cmp);
                                cmp.show();
                            },
                            flex: 0,
                            overCls: 'o_button',
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABBklEQVQ4T+2TwU3DQBRE31QAHUAHhApwbtygA6ACoALogHQAdEAqIOkgdBA6yJXToLH+IjsSsrjzL2tb+9+fmV3L9iNwBbxKyvNkjXps74AD4FPS8WQ3YHsLHPU9thfANbD4o4K7vsd2pl6UhV29h/4BzICtpEz8KduHZXsZwFsBNpJOy98D8FLKlpIuW3c1vxe8B6yAs9qwAQL8As7r+1pSZzuSk1VgUZZaDwGRHEAsZc2mgBsgWfWWaj3ZB7SNCfR2MGVkIWMHqkcKGiABNYnZn2xy1MMQm+0eEG9PwI2kBDdZtqPyGbgPoAOS6lxSyJM16vkHzNu/kPBm+8f1W5p1nXPZum/qlbRhokYlqwAAAABJRU5ErkJggg==',
                            text: 'Servizi',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {

                                Ext.getCmp("mainCont").removeAll();
                                var cmp = Ext.create("Rai.view.frmLotti");
                                Ext.getCmp("mainCont").add(cmp);
                                cmp.show();
                            },
                            flex: 0,
                            hidden: true,
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABL0lEQVQ4T42TjU0CQRCF31SgHUgH2oF0IB1oB1qKJVwJ0AF0cHQAHWAFY75zHllw9dhkc8nuzrx5PxeaWZm5iIjDX8+id5GZT5JeJa0kLSSdJI2StrX3EcGZzg1AkvQi6U0SDeYWDdeRmRSAtpyruLr/kjTQgLGebyymaD0hR/D9oZCZ9zUBnJnkoWl4UVT6vNe7kQk+ivskUkRsSg8anUDqiEr/vSkwCo/vGlSrzWR2gutjURgiAsALF2ji3WpyLpJEHnCKpuwtFD7r0Ki78h0roTBmJo9dyFSsjW0cOsKBREMWxS6CN4C40A0SFOyENZnEKu40bMN2gAIicmgKOLEr5UFhc49bTqitnYLEBaitcM4+iE7orxBdu+Aw2YnHVqyWd5va7t/odFqo/2L+DQX7j2UlvC6TAAAAAElFTkSuQmCC',
                            text: 'Lotti',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {

                                Ext.getCmp("mainCont").removeAll();
                                var cmp = Ext.create("Rai.view.frmProduzioni");
                                Ext.getCmp("mainCont").add(cmp);
                                cmp.show();
                            },
                            flex: 0,
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA8ElEQVQ4T6WS7VECQRBEX0egIZgBkgEhkIGSgUYgREAIagRqBhCBmMGRAUbQVFMLtbdWIVfMv/2YN929K64sXdnPYIDtW2AE/EjaDQLYvgO+gUB2wGwo4A14qGx3PUCR91omPEva1BnZbgHbFvAELEvTWtKkAdwDK+Cm7Pct2J4DL+VwI2ncAJJBhgTSReFJge3QH4HIzMUulyVl71DFQvYS4KFU+fqSNG0mpjk28myphaTP+k4A/sdznu1Y77Wio4JMja9Ia1PP2UcF+KPy7D8oz5rAYuEXmErK+lQXfSTbySGpJ9heXQRomwYrOAfYAyRmYXRsAIwwAAAAAElFTkSuQmCC',
                            text: 'Produzioni',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {

                                Ext.getCmp("mainCont").removeAll();
                                var cmp = Ext.create("Rai.view.frmLuoghi");
                                Ext.getCmp("mainCont").add(cmp);
                                cmp.show();
                            },
                            flex: 0,
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABJUlEQVQ4T7WT/VHCQBDFf68CpALpQKxAqIDYgZRgB5agHViCVkCoQKgAOhAqWOdl9piYaOAfbubmkru3b99+iQtWRMyAB6CWtG6baMg+Im6AFTAGNsAU+Abmkg62VUR8AF8JWJcHP0bEO2CSJ2ABfAK+O0jyXUMQwFuyW+Y+9wTwvgde83sHPKdD4+qGQNIplIzXsufprUqCWzsE/F/nueoRpPSGNMMz2GFasuU7oZWkqnHeVdAhMNjGE+cmk+p8LSXVZwlaiRxJekxF2PvJ0ZCCBLkKDmMEHB1CqdRFClokrv+4U+bhHLSb7F+l50IoJNclAF4yUdssV+kDJ/Aua29MHxcRbhAPiWtucBmacm7zzq1rwl+43jRmKxvk0XX5/lyJm/4AzAPp7iVsqWEAAAAASUVORK5CYII=',
                            text: 'Luoghi',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {

                                Ext.getCmp("mainCont").removeAll();
                                var cmp = Ext.create("Rai.view.frmProfiliManager");
                                Ext.getCmp("mainCont").add(cmp);
                                cmp.show();
                            },
                            flex: 0,
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABB0lEQVQ4T72TUXXCQBBF71MADoqDFgXUQXFAq6DggCgoEqgCkBAcgAPqAAfDeTm7kBPSJF/M5+7MnZn3dkVPRMQc+AYmQAmsJF1ymbrqI2IJ/DRyzsA0Q/oA7jRqaeIpNj7vA8Q/ExaS1kMAHvelBfIlaTsEYAF3DcBJ0tsgEZ0UEe+AxRwnFzaDXEiFts9T1MNWlpKKaoWIsBhtYrlzjj/AY7/Wzo6SpgaYVk9+0Cw1cc6scVncABExkXROyR7TDly8bwfgUAd4FRe6k5+tYyup7ABUGlQrpKQ8YV5p/RTAHjim1vY6K31oCNYm4v0vJN8/gUUq/AUMt5h+SB+A7fQH85n12l8BmYmISPEQTG0AAAAASUVORK5CYII=',
                            text: 'Profili',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                Ext.getCmp("mainCont").removeAll();
                                //var panel = Ext.create("Rai.view.frmReports");
                                var panel = Ext.create("Rai.view.frmReportManager");
                                Ext.getCmp("mainCont").add(panel);
                                panel.show();

                            },
                            flex: 0,
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABDklEQVQ4T5WTsU0EQQxF34cGjogQkCjgqIBDogBKoAOOlIQWLiKGi8hYYpIlJoACkKgAQQdG/+QV3Gpn53CyK9vzbI//CCAivoE3/29gU0mTLk8JaCXNNjjsYi1wDuxJel4DRMQ9sD0CugZuEtBImvYBu8DKV7BP4MnduhN/+4BTYGsE8AI8jAGuKoAlsCwChipHxESSt7SyrvXBEfqAiGiAY+CggxQBwJmTJT1mJe/aKzPEsQ/gDpgPjpDJXtOJpDYiFvZJajxGCu0WmJUArmIxzYEvr1OSfWtWvYOI2M92LyW5i/8BanIudeCHdFE7nPGFpKP+GruHdAi810B5yb9S/iMSC+a1Bsi4n/XOD3JtxhH6xGSsAAAAAElFTkSuQmCC',
                            text: 'Analytics',
                            textAlign: 'left'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                Ext.getCmp("pageContainer").removeAll();
                                var cmp = Ext.create("Rai.view.frmLogin");
                                Ext.getCmp("pageContainer").add(cmp);
                                cmp.show();
                            },
                            flex: 0,
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAsklEQVQ4T7WT0Q2BMRSFv25gAzEBG2ADIxiBCdjECDzw7PfMAxuwgQ2O3CiRX1O3adykL83t13NuTwOVFSrPkwRIWgLDH/A7MP8CSJoCK6eyJgWw2xdOwNOCpA6wBi6ASfMD4uE90ANGwKQUcAb6wDWuHXBKWDCVZs963xUkvQC3CNgCxwxg0AYYuQG6wLjYwscQNxFkW/4htqXGEFUBSoJ0yEXZnjRXlpfZfz6TN8bW9wC4okCk0g7hvgAAAABJRU5ErkJggg==',
                            text: 'Logout',
                            textAlign: 'left'
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onPanelAfterRender'
    }

});