/*
 * File: app/view/frmServiziManager.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.frmServiziManager', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.frmServiziManager',

    requires: [
        'Rai.view.frmServiziViewModel7',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.form.field.Text',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.grid.plugin.CellEditing'
    ],

    viewModel: {
        type: 'frmservizimanager'
    },
    id: 'frmServiziManager',
    title: '',

    layout: {
        type: 'border',
        padding: 1
    },
    items: [
        {
            xtype: 'panel',
            region: 'center',
            padding: 1,
            layout: 'fit',
            iconCls: '',
            title: '',
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'serviziGrid2',
                    glyph: '',
                    iconCls: '',
                    title: 'Elenco Servizi',
                    store: 'storeServizi',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 129,
                            dataIndex: 'lotto',
                            text: 'Lotto',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 129,
                            dataIndex: 'descrizione',
                            text: 'Descrizione',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 129,
                            dataIndex: 'codice',
                            text: 'Voce',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'tipologia',
                            text: 'Tipologia',
                            flex: 0.6,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'importo',
                            text: 'Importo',
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'note',
                            text: 'Note',
                            flex: 1.2,
                            editor: {
                                xtype: 'textfield'
                            }
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'storeServizi'
                        }
                    ],
                    plugins: [
                        {
                            ptype: 'cellediting'
                        }
                    ]
                }
            ]
        }
    ]

});