/*
 * File: app/view/nuovaProduzione.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.nuovaProduzione', {
    extend: 'Ext.window.Window',
    alias: 'widget.nuovaProduzione',

    requires: [
        'Rai.view.nuovaProduzioneViewModel',
        'Ext.button.Button',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'nuovaproduzione'
    },
    height: 174,
    width: 432,
    layout: 'absolute',
    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABS0lEQVQ4T6WTQU7CQBSG35shMS6IHAGXxrTFhdplj8ANxAMg0xOoJ2goBxBPoN6g7oouwFbj0noDiCaayPSZqZR0CCE2neWb9775/39mECourDgPpQEt762xzT+sL1l/mri701IA23ttEvsZI2KDiKbE4LQcoB8NAfFkaZso0QBK3hb/vEKAhpTMfXT3J8WM7FUAwLsGOPafBQJ5i6H78MxwioBD76XFuAwQcOevTroFux9fAMJ5tkUwGfWMA01BlsFcEKOA5jxRCpcKMjpLO2nKhliTTdXAmRRhz+zkEGXhO60LlX5ew9wXEd2NemZbO9GPOkDgEKCVqWJ0+dA1b4s9aPsxbfLMeToupH5dVKTqeDSI2oxQSMnEauqLvZscsE7lxnewuNYAASwCmiFiO+wagWbhP3/BHsQOzGtJ6O4lq/2lXuK6wyoDfgE/B5Lv6ZyygwAAAABJRU5ErkJggg==',
    iconCls: '',
    title: 'Nuova produzione',
    titleAlign: 'center',
    modal: true,

    items: [
        {
            xtype: 'button',
            handler: function(button, e) {
                this.up('window').close();
            },
            x: 260,
            y: 100,
            width: 90,
            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAz0lEQVQ4T6WTYRWCQBCEv00gETCBNlAbUMEEQgONYAMj2EAjGMEINFjf8MAHxyEC9/duvp2d3TMWHovp3T0BEjN7j/F7gFr8AAoze04CtMRb4DAJEIhV+H9ARNw4fwFq4zqUh/0Qh+3fgaOZle0LAVRhNxZWfS+xWpOz6gigwARZzYFUY5wBkQM5Kb97EIEUQGN1D2TApuXyYmbnziIFkN4Y3T0FcuAEKI91bBObTLKhRXJ3OboBXQeNvdoJ7bTDgOs3efQz/TkNhZ8uAqjQBy4jVzUc52twAAAAAElFTkSuQmCC',
            text: 'Annulla'
        },
        {
            xtype: 'button',
            handler: function(button, e) {
                var win = this.up('window');
                var nome = Ext.getCmp('nomeProd').getValue();
                var matricola = Ext.getCmp('nomeMatricola').getValue();

                if (nome === undefined || nome == "" ){
                    Ext.Msg.show({
                        title:'Errore',
                        msg: "Il nome della produzione non può essere vuoto!",
                        buttons: Ext.Msg.Ok,
                    });
                    return;
                }

                var store = Ext.StoreManager.lookup('storeProduzioni');
                var emptyApp = new Rai.model.produzioni();
                emptyApp.set("descrizione",nome);
                emptyApp.set("divisione",USER.divisione);
                emptyApp.set('matricola',matricola);
                store.add(emptyApp);
                store.on('write', function() { store.load(); win.close();});



            },
            x: 80,
            y: 100,
            width: 170,
            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAu0lEQVQ4T+2TyxHCMAxE31YAdEAHQCdQAaQykgqglJRACVDBMvY4GefjAHd8skfaN5JWFgvH9hOwpE0pTR8ADnFJxbw/AAYzsL0GtpLaMDzbgyHa3gMPScGdeMaAINwBlaQ6B9i+AFeglXQoAWrgnIJVEoRnfm8kBdi0glR2DhmvyUA8aaHLtj0HmYiLgJlKZsWLgAwSVrnvedxT70KyaLX0N7LYq7M6AjKLvtTHtGh1BzgCt1/UwEnS/Q3QE10RCutRsgAAAABJRU5ErkJggg==',
            text: 'Salva'
        },
        {
            xtype: 'textfield',
            x: 80,
            y: 60,
            id: 'nomeMatricola',
            width: 270,
            fieldLabel: 'Matricola'
        },
        {
            xtype: 'textfield',
            x: 80,
            y: 30,
            id: 'nomeProd',
            width: 270,
            fieldLabel: 'Produzione'
        }
    ]

});