/*
 * File: app/view/uploadWin.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.uploadWin', {
    extend: 'Ext.window.Window',
    alias: 'widget.uploadWin',

    requires: [
        'Rai.view.uploadWinViewModel',
        'Rai.view.uploadWinViewController',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.File'
    ],

    config: {
        storeLocale: '{descr:"ok"};'
    },

    controller: 'uploadwin',
    viewModel: {
        type: 'uploadwin'
    },
    height: 242,
    id: 'uploadWin',
    width: 656,
    layout: 'absolute',
    bodyStyle: 'color:white;',
    title: 'Upload file',
    titleAlign: 'center',

    items: [
        {
            xtype: 'button',
            handler: function(button, e) {


                var filefield = Ext.getCmp('fileUpload');
                var file = filefield.getEl().down('input[type=file]').dom.files;
                debugger;
                var reader = new FileReader();
                var idRichiesta = this.up('window').idRichiesta;

                reader.onload = (function(theFile) {
                    return function(e) {
                        var encodedFile = Ext.util.base64.encode(e.target.result);

                        Ext.Ajax.request({
                            method : 'POST',
                            url: '/richiestaNuovoServizio/report',
                            headers: {
                                'Authorization': 'Bearer ' + ACCESS_TOKEN,
                                'Content-Type': 'application/json'
                            },
                            jsonData: {
                                id : idRichiesta,
                                data : encodedFile
                            },
                            success: function (response, options) {
                                Ext.Msg.show({
                                    title:'Benvenuto',
                                    msg: "Risultato: " + response.responseText,
                                    buttons: Ext.Msg.Ok,
                                });},
                                failure: function (response, options) { Ext.Msg.show({
                                    title:'Errore con il server',
                                    msg: "Risposta: " + response,
                                    buttons: Ext.Msg.Ok,
                                });
                            }
                        });



                    };
                })(file);
                // start upload
                reader.readAsBinaryString(file);
            },
            x: 110,
            y: 170,
            height: 30,
            width: 420,
            text: 'Invia file'
        },
        {
            xtype: 'gridpanel',
            x: -4,
            y: 0,
            id: 'fileGrid',
            header: false,
            title: 'My Grid Panel',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'Nome file',
                    flex: 2
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Dimensioni',
                    flex: 1
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'filefield',
                            id: 'fileUpload',
                            width: 71,
                            fieldLabel: '',
                            hideEmptyLabel: false,
                            hideLabel: true,
                            labelWidth: 0,
                            buttonMargin: 0,
                            buttonOnly: true,
                            buttonText: 'Aggiungi',
                            listeners: {
                                change: 'onFileUploadChange'
                            }
                        },
                        {
                            xtype: 'button',
                            style: 'color:white;background-color:#EF9A9A;',
                            text: 'Rimuovi'
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        show: 'onUploadWinShow',
        afterrender: 'onUploadWinAfterRender'
    }

});