package com.hequalab.rai.api.dtos.fornitori;

/*
 * Class generated by AppWizard
 */




public class FornitoriUpdate {

	private String note;
	private String ragioneSociale;

    private FornitoriUpdate() {
    }


	public String getNote() {
		return note;
	}
	
	public void setNote(String note) {
		this.note = note;
	}


	public String getRagioneSociale() {
		return ragioneSociale;
	}
	
	public void setRagioneSociale(String ragioneSociale) {
		this.ragioneSociale = ragioneSociale;
	}

	
}