package com.hequalab.rai.domain.richiestanuovoservizio.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultAggregateDeleted;
import com.hequalab.rai.domain.richiestanuovoservizio.RichiestaNuovoServizioId;

public class RichiestaNuovoServizioDeleted extends DefaultAggregateDeleted<RichiestaNuovoServizioId> {

	private static final long serialVersionUID = 1L;

	
	@SuppressWarnings("unused")
	private RichiestaNuovoServizioDeleted() {
	}

	public RichiestaNuovoServizioDeleted(RichiestaNuovoServizioId id) {
		super(id);
	}				

}