package com.hequalab.rai.api.dtos.filiali;

/*
 * Class generated by AppWizard
 */




public class FilialiUpdate {

	private String nome;

    private FilialiUpdate() {
    }


	public String getNome() {
		return nome;
	}
	
	public void setNome(String nome) {
		this.nome = nome;
	}

	
}