/*
 * File: app/view/frmAdmin.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.frmAdmin', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.frmAdmin',

    requires: [
        'Rai.view.frmFilialeViewViewModel2',
        'Rai.view.frmFilialeViewViewController2',
        'Ext.panel.Panel',
        'Ext.button.Button'
    ],

    controller: 'frmadmin',
    viewModel: {
        type: 'frmadmin'
    },
    id: 'frmAdmin',
    layout: 'fit',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'panel',
            id: 'frmFiliale_ex1',
            title: 'Gestione Lavorazioni - Pannello amministrazione',
            titleAlign: 'center',
            layout: {
                type: 'border',
                padding: 1
            },
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    id: 'mainCont1',
                    layout: 'fit',
                    title: ''
                },
                {
                    xtype: 'panel',
                    region: 'west',
                    id: 'frmFiliale_button1',
                    width: 150,
                    bodyPadding: 10,
                    collapsible: true,
                    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAADK0lEQVRYR81XXVIaQRjsJhiSkiXkBFlPIJ4g5ATiCWIeXR6EE4gnEB/Ax+AJxBuQE4gncHKCrCypFErxpWbGJcOPuBtJRZ6E+fn+untaIsXHP/vlY3J/BeKLCgpd96jfHlQg+Io7b0vVGSa9lkk3xvv8VtREJttUB2/VTAImuXFNVb1amjtTJ5Dm8iR7X14CfmtYAuUIIiHuvLo7TzNn8BBETx14xzMjaEUNEB8BOXXx4Z9IEa+jE5BFCI9VNd93zy10wG9FXRK7epOAdRXkm/GBrfYgBPjOrAl34st00qRc2d8lVNXCewczDRJHdg2XqupVVifQHnQIfl6aQGugQH5YlQBEvt9UC/40gfawRsiJvU/OVVDYX52Ablnup9nkVq+/m/FAKqD0l9OQJWSynQWGtIeWGaPNzjxFXx4Ik1BnnXsSd8CgOTc8gqAMQoHZetxqo5AyPoHA1wzBKH+cVA2pD7szm0oqEYIbn6ZBWlGTxGFcvQj6qurtGGy0oz6BbWftNFZES+vJBQTFeQnXsampJcLO9EA76hGaz4Y2x6rqNZYFMeujvKEbc8Mf7lgEuFaBV7LAjf7QEPimAq/88HsTkM80FXOj71TqHJC9GO2uPthgcnsTFIr6L1cf5vmu7yd4sVCQGdt9aSkGTNsyr8KZ0dg5d22r5VbIijrweqaas6hMka4WKV09mK3MnDX0BeZV0HQvLaI1GB8D2Kq1x+K8zASs4s22zJqR8QWJktZ7ZLg3HcGDGSFZ1OxAJruXeAR/C0L30XkWCP8nDUnZ5zxwLG3QgSCUzEb5USFyuf6EEBGTLoiiAPvzXiExCK2xGGrTUYZAIZOtzUjxZNwE4UPQw12+kViK09Jw3fsTd2DdgeP7Fi2ZbvWb4SEmDFU1f+oGtgopuxC5XmpIyG1MeDmveL42JALB3eb5k4bEX2XJknhCiFJBYStOXAdPZ8meaUrdR8q+ok4CiUyp9X0NUEKMvNoSW67b2Yuf6Wml1paXAWku2PJc1ISwCLDxpC3/V2Bb22O07gRT03DlP6cyPlSBV0+TZKoEjIeT+/68pFqwWQmXkecnVUF97jfBj0/qfJSTfwAAAABJRU5ErkJggg==',
                    title: 'Menù',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'button',
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABZElEQVQ4T32TYVEDUQyEdxVAHZwDqAKKAnBAqwBQQFFAq4CrAiqhKKA4wAFFQZjvJu/m3c1c359rX5LN7ibPGp2IWEi6k3Q9Ch0l7Wzz7Y/Lr4i4lPQuaSZpI+kkKTJOHvEnSb+SVraJqwYAmcIfSW8TDJ4lNQDZ7hh2ABGxzk4Uw+LcWSWIbK8LAIVo/0qqf5IuJlCgPpd0sN04IqDUciHpJYu2+X2cAHnNhksA6LxMWjdZcGv7EBH3GSMHj9ANs880eQMA3R+qTjjMXX+S5QnnI4JJYDJnC0AZFRezTNozDdskYzLTaWzDiP99zQDAdjEVSQDgCwVIAKDNfWEXugMA2q5q7edmmL58ZM43AGwY5kAPL1iSXXYeMMk7/GGUyDz2m5hB9gHajBbgwmzOG4gIGu2Zfy9h5HaXkGwAgwHuo72P1Q9qwKCijevoLONEHiu8mHyNIybQp3s3tmTVlhdY5/4DVEimyi/1uJ8AAAAASUVORK5CYII=',
                            text: 'Richieste',
                            textAlign: 'left',
                            listeners: {
                                click: {
                                    fn: 'onRichiesteClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABBklEQVQ4T+2TwU3DQBRE31QAHUAHhApwbtygA6ACoALogHQAdEAqIOkgdBA6yJXToLH+IjsSsrjzL2tb+9+fmV3L9iNwBbxKyvNkjXps74AD4FPS8WQ3YHsLHPU9thfANbD4o4K7vsd2pl6UhV29h/4BzICtpEz8KduHZXsZwFsBNpJOy98D8FLKlpIuW3c1vxe8B6yAs9qwAQL8As7r+1pSZzuSk1VgUZZaDwGRHEAsZc2mgBsgWfWWaj3ZB7SNCfR2MGVkIWMHqkcKGiABNYnZn2xy1MMQm+0eEG9PwI2kBDdZtqPyGbgPoAOS6lxSyJM16vkHzNu/kPBm+8f1W5p1nXPZum/qlbRhokYlqwAAAABJRU5ErkJggg==',
                            text: 'Servizi',
                            textAlign: 'left',
                            listeners: {
                                click: {
                                    fn: 'onClickServizi',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAApklEQVQ4T9WSYQ3CQAyFvzpAwhwggTlAwxQACgAHQwHgABTAHDBFj1zCJbeDW/eDkNB/fW2+5rU1SS2wYhiNmZ0y7WNqku7AIqvuzWz3G8CUKWM9wULYwTxrOv/RDrwrSJoBW6CPtgbaGEBSDRyBCujMrH7TCoADIGCdLLcHbpnWlR5p6nVdwAZ4vCZHaKq5gGAhAMK7x0g1F+BZ+Q7gAiy9UYX69QmzDGhG6nj6JgAAAABJRU5ErkJggg==',
                            text: 'Divisioni',
                            textAlign: 'left',
                            listeners: {
                                click: 'onButtonClick11'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABT0lEQVQ4T5WTsVEDQQxF368AEnJcAbgCcAWYCjARAQE4hQBTAZc7gBLMDDmmAhwRQwVcB2K+Wd3cnDGGjfZ2V09f+jrRWhExAi6AuaRx+27dXh1AtL4HkuabIF3AAtgrQT1J7/8FbAMuY/aXYMMbBRGRwUNgKKnelL0LuARugGvgrV1/ROwDWwmU9NLsvYkIZ/UjA86BHX9LOi73VtMAgL4k9+u7hIiYAU/AtCPbLtjO185545BK7Z/AGXDlGQAegMPSUO+tMN358F022QA/fAYss5J0m9kiwjAP1eTXQYqIdo0OOnWGBACeh/sfIHX2wDJPWg8M7JdSchrd4JWVAFt4BzwCu6XeAWDpBhjo+1VA8Ti77KwVcCDJ/Vn2oJzZ5u6q/SjnfyypiojlD1UAtvdoTQOtqpdZFpJcRs5ELWlULLaF/j+szEFWYucmHqYvzmeQL0fpN/gAAAAASUVORK5CYII=',
                            text: 'Fornitori',
                            textAlign: 'left',
                            listeners: {
                                click: 'onFornitoriClick'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABB0lEQVQ4T72TUXXCQBBF71MADoqDFgXUQXFAq6DggCgoEqgCkBAcgAPqAAfDeTm7kBPSJF/M5+7MnZn3dkVPRMQc+AYmQAmsJF1ymbrqI2IJ/DRyzsA0Q/oA7jRqaeIpNj7vA8Q/ExaS1kMAHvelBfIlaTsEYAF3DcBJ0tsgEZ0UEe+AxRwnFzaDXEiFts9T1MNWlpKKaoWIsBhtYrlzjj/AY7/Wzo6SpgaYVk9+0Cw1cc6scVncABExkXROyR7TDly8bwfgUAd4FRe6k5+tYyup7ABUGlQrpKQ8YV5p/RTAHjim1vY6K31oCNYm4v0vJN8/gUUq/AUMt5h+SB+A7fQH85n12l8BmYmISPEQTG0AAAAASUVORK5CYII=',
                            text: 'Profili',
                            textAlign: 'left',
                            listeners: {
                                click: 'onButtonClick2'
                            }
                        },
                        {
                            xtype: 'button',
                            icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAsklEQVQ4T7WT0Q2BMRSFv25gAzEBG2ADIxiBCdjECDzw7PfMAxuwgQ2O3CiRX1O3adykL83t13NuTwOVFSrPkwRIWgLDH/A7MP8CSJoCK6eyJgWw2xdOwNOCpA6wBi6ASfMD4uE90ANGwKQUcAb6wDWuHXBKWDCVZs963xUkvQC3CNgCxwxg0AYYuQG6wLjYwscQNxFkW/4htqXGEFUBSoJ0yEXZnjRXlpfZfz6TN8bW9wC4okCk0g7hvgAAAABJRU5ErkJggg==',
                            text: 'Logout',
                            textAlign: 'left',
                            listeners: {
                                click: {
                                    fn: 'onLogoutClick',
                                    scope: 'controller'
                                }
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: {
            fn: 'onPanelAfterRender',
            scope: 'controller'
        }
    },

    onButtonClick11: function(button, e, eOpts) {

        Ext.getCmp("mainCont1").removeAll();
        var cmp = Ext.create("Rai.view.frmFiliali");
        Ext.getCmp("mainCont1").add(cmp);
        cmp.show();
    },

    onFornitoriClick: function(button, e, eOpts) {

        Ext.getCmp("mainCont1").removeAll();
        var cmp = Ext.create("Rai.view.frmFornitori");
        Ext.getCmp("mainCont1").add(cmp);
        cmp.show();
    },

    onButtonClick2: function(button, e, eOpts) {

        Ext.getCmp("mainCont1").removeAll();
        var cmp = Ext.create("Rai.view.frmProfili");
        Ext.getCmp("mainCont1").add(cmp);
        cmp.show();
    }

});