/*
 * File: app/view/frmFilialeViewViewController1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.frmFilialeViewViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.frmservizigenerali',

    onPanelAfterRender: function(component, eOpts) {
        var store = Ext.StoreManager.lookup('storeRichiesteServizi');

        store.filter({
            property: "divisione",
            value: USER.divisione ,
            operator: "streq"
        });


        var richieste = 0;
        Ext.Ajax.request({
            url: '/richiestaNuovoServizio/attesaApprovazione/' + USER.divisione,
            headers: {
                'Authorization': 'Bearer ' + ACCESS_TOKEN,
            },
            success: function (response, options) {
                Ext.Msg.show({
                    title:'Benvenuto',
                    msg: "Ci sono " + response.responseText + " richieste in attesa di approvazione.",
                    buttons: Ext.Msg.Ok,
                });},
                failure: function (response, options) { Ext.Msg.show({
                    title:'Errore con il server',
                    msg: "Risposta: " + response,
                    buttons: Ext.Msg.Ok,
                });
            }


        });


        Ext.getCmp("mainCont").removeAll();
        var cmp = Ext.create("Rai.view.frmServGenerali");
        Ext.getCmp("mainCont").add(cmp);
        cmp.show();

        var store2 = Ext.StoreManager.lookup('storeServizi').load();


    }

});
