/*
 * File: app/view/frmFiliali.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.frmFiliali', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.frmfiliali',

    requires: [
        'Rai.view.frmServiziViewModel3',
        'Rai.view.frmServiziViewController3',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'frmfiliali',
    viewModel: {
        type: 'frmfiliali'
    },
    height: 753,
    padding: 0,
    width: 1099,
    title: 'Area divisioni',

    layout: {
        type: 'border',
        padding: 1
    },
    items: [
        {
            xtype: 'panel',
            region: 'center',
            padding: 1,
            layout: 'fit',
            title: '',
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'filialeGrid',
                    title: 'Elenco divisioni',
                    store: 'storeFiliali',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'nome',
                            text: 'Descrizione',
                            flex: 1
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'storeFiliali'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            width: 330,
            bodyPadding: 10,
            title: '',
            items: [
                {
                    xtype: 'textfield',
                    id: 'nomeFilialeTxt',
                    fieldLabel: 'Divisione :'
                },
                {
                    xtype: 'button',
                    text: 'Salva',
                    listeners: {
                        click: 'onSave'
                    }
                },
                {
                    xtype: 'button',
                    text: 'Elimina',
                    listeners: {
                        click: 'onDelete'
                    }
                },
                {
                    xtype: 'button',
                    text: 'Annulla',
                    listeners: {
                        onClear: 'onButtonOnClear'
                    }
                }
            ]
        }
    ]

});