/*
 * File: app/view/frmServiziViewController1.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.frmServiziViewController1', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.frmfornitori',

    onSave: function(button, e, eOpts) {
        var ragioneSociale = Ext.getCmp('ragioneSocialeTxt').getValue(),
            note = Ext.getCmp('noteTxt').getValue();

        if (ragioneSociale === undefined || ragioneSociale === null || ragioneSociale === ""){
            Ext.Msg.show({
                title:'Errore',
                msg: "La ragione sociale non puo' essere vuota!",
                buttons: Ext.Msg.Ok,
            });
            return;
        }

        var store = Ext.StoreManager.lookup('storeFornitori');
        var emptyApp = new Rai.model.fornitori();
        emptyApp.set('ragioneSociale',ragioneSociale);
        emptyApp.set('note',note);
        store.add(emptyApp);
        store.on('write', function() { store.load();});
    },

    onDelete: function(button, e, eOpts) {
        var selection = Ext.getCmp('fornitoriGrid').getSelectionModel().getSelection();
        var store = Ext.StoreManager.lookup('storeFornitori');
        store.remove(selection);
    },

    onButtonClick: function(button, e, eOpts) {
        Ext.getCmp('ragioneSocialeTxt').setValue("");
        Ext.getCmp('noteTxt').setValue("");
    }

});
