/*
 * File: app/view/winNuovaTipologiaServizioViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.winNuovaTipologiaServizioViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.winnuovatipologiaservizio',

    id: 'popWin',

    onAddRichiesta: function(button, e, eOpts) {
        var descrizione = Ext.getCmp('descrizioneTipologiaTxt').getValue(),
            nome = Ext.getCmp('nomeTipologiaTxt').getValue(),
            stato = "Non Approvato";

        if (nome === undefined || nome === "")
        {    Ext.Msg.show({
            title:'Errore',
            msg: "Il nome non puo' essere vuota!",
            buttons: Ext.Msg.Ok,
        });
        return;
    }

    if (descrizione === undefined || descrizione === "")
    {    Ext.Msg.show({
        title:'Errore',
        msg: "La descrizione non puo' essere vuota!",
        buttons: Ext.Msg.Ok,
    });
    return;
}


var store = Ext.StoreManager.lookup('storeRichiesteTipologie');
var emptyApp = new Rai.model.richiestaTipologia();
emptyApp.set('descrizione',descrizione);
emptyApp.set('nome',nome);
emptyApp.set('filiale',USER.divisione);
emptyApp.set('stato',stato);
store.add(emptyApp);
var self = this;
store.on('write', function() {
    Ext.getCmp('winnuovatipologiaservizio').destroy();
});
    },

    onWinnuovatipologiaservizioDestroy: function(component, eOpts) {
        Ext.getCmp('popButton').enable();
    }

});
