/*
 * File: app/view/winNuovaTipologiaServizio.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Rai.view.winNuovaTipologiaServizio', {
    extend: 'Ext.window.Window',
    alias: 'widget.winnuovatipologiaservizio',

    requires: [
        'Rai.view.winNuovaTipologiaServizioViewModel',
        'Rai.view.winNuovaTipologiaServizioViewController',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    controller: 'winnuovatipologiaservizio',
    viewModel: {
        type: 'winnuovatipologiaservizio'
    },
    height: 190,
    id: 'winnuovatipologiaservizio',
    width: 388,
    bodyPadding: 10,
    title: 'Richiesta nuova tipologia di servizio',

    items: [
        {
            xtype: 'textfield',
            id: 'nomeTipologiaTxt',
            fieldLabel: 'Nome'
        },
        {
            xtype: 'textareafield',
            id: 'descrizioneTipologiaTxt',
            fieldLabel: 'Descrizione '
        },
        {
            xtype: 'button',
            flex: '1',
            width: 360,
            text: 'Richiedi',
            listeners: {
                click: 'onAddRichiesta'
            }
        }
    ],
    listeners: {
        destroy: 'onWinnuovatipologiaservizioDestroy'
    }

});