package com.hequalab.rai.domain.fornitori;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.domain.fornitori.events.FornitoriCreated;
import com.hequalab.rai.domain.fornitori.events.FornitoriDeleted;
import com.hequalab.rai.domain.fornitori.events.FornitoriUpdated;
import com.hequalab.rai.dddd.DeletableAggregate;


public class Fornitori extends DeletableAggregate<Fornitori,FornitoriId,FornitoriDeleted> {

	private Fornitori(FornitoriId id) {
		super(id, FornitoriDeleted.class);
	}

	public Fornitori(FornitoriId id ,String note,String ragioneSociale) {
		this(id);
		applyChange(new FornitoriCreated(id , note, ragioneSociale));
	}
	
	public Fornitori update( String note,String ragioneSociale) {
		applyChange(new FornitoriUpdated(getId() , note, ragioneSociale));
		return this;
	}

}