package com.hequalab.rai.domain.fornitori;

/*
 * Class generated by AppWizard
 */
 
import com.hequalab.rai.dddd.UUIDIdentity;

public class FornitoriId extends UUIDIdentity {
	
	private static final long serialVersionUID = 1L;
	
	public FornitoriId() {
		super();
	}

	public FornitoriId(String uuid) {
		super(uuid);
	}

}