package com.hequalab.rai.api.dtos.lotti;

/*
 * Class generated by AppWizard
 */




public class LottiUpdate {

	private String descrizione;
	private String divisione;
	
    private LottiUpdate() {
    }


	public String getDescrizione() {
		return descrizione;
	}
	
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}


	public String getDivisione() {
		return divisione;
	}


	public void setDivisione(String divisione) {
		this.divisione = divisione;
	}

	
}