package com.hequalab.rai.api.params;

/*
 * Class generated by AppWizard
 */

import io.dropwizard.jersey.params.AbstractParam;
import com.hequalab.rai.domain.fornitori.FornitoriId;

public class FornitoriIdParam extends AbstractParam<FornitoriId> {

	public FornitoriIdParam(String input) {
		super(input);
	}

	@Override
	public FornitoriId parse(String input) throws Exception {
		return new FornitoriId(input);
	}

}