package com.hequalab.rai.api.params;

/*
 * Class generated by AppWizard
 */

import io.dropwizard.jersey.params.AbstractParam;
import com.hequalab.rai.domain.lotti.LottiId;

public class LottiIdParam extends AbstractParam<LottiId> {

	public LottiIdParam(String input) {
		super(input);
	}

	@Override
	public LottiId parse(String input) throws Exception {
		return new LottiId(input);
	}

}