package com.hequalab.rai.api.params;

/*
 * Class generated by AppWizard
 */

import io.dropwizard.jersey.params.AbstractParam;
import com.hequalab.rai.domain.luoghi.LuoghiId;

public class LuoghiIdParam extends AbstractParam<LuoghiId> {

	public LuoghiIdParam(String input) {
		super(input);
	}

	@Override
	public LuoghiId parse(String input) throws Exception {
		return new LuoghiId(input);
	}

}