package com.hequalab.rai.api.params;

/*
 * Class generated by AppWizard
 */

import io.dropwizard.jersey.params.AbstractParam;
import com.hequalab.rai.domain.produzioni.ProduzioniId;

public class ProduzioniIdParam extends AbstractParam<ProduzioniId> {

	public ProduzioniIdParam(String input) {
		super(input);
	}

	@Override
	public ProduzioniId parse(String input) throws Exception {
		return new ProduzioniId(input);
	}

}