package com.hequalab.rai.api.params;

/*
 * Class generated by AppWizard
 */

import io.dropwizard.jersey.params.AbstractParam;
import com.hequalab.rai.domain.servizi.ServiziId;

public class ServiziIdParam extends AbstractParam<ServiziId> {

	public ServiziIdParam(String input) {
		super(input);
	}

	@Override
	public ServiziId parse(String input) throws Exception {
		return new ServiziId(input);
	}

}