package com.hequalab.rai.api.read.views.fornitori;

/*
 * Class generated by AppWizard
 */

import org.hibernate.SessionFactory;
import com.hequalab.rai.api.read.views.AbstractViewWriter;
import com.hequalab.rai.api.write.ApiContext;
import com.hequalab.rai.dddd.EventListener;
import com.hequalab.rai.dddd.EventStream;
import com.hequalab.rai.domain.fornitori.events.FornitoriCreated;
import com.hequalab.rai.domain.fornitori.events.FornitoriDeleted;
import com.hequalab.rai.domain.fornitori.events.FornitoriUpdated;



public class FornitoriViewWriter extends AbstractViewWriter<FornitoriView> {

	public FornitoriViewWriter(SessionFactory sessionFactory) {
		super(sessionFactory, FornitoriView.class, "fornitoriId");
	}

	@EventListener
	public void apply(FornitoriCreated event, EventStream<ApiContext> stream) {
		FornitoriView u = new FornitoriView();
		u.setFornitoriId(event.getId());
		u.setNote(event.getNote());
		u.setRagioneSociale(event.getRagioneSociale());
		session().save(u);
	}

	@EventListener
	public void apply(FornitoriUpdated event, EventStream<ApiContext> stream) {
		FornitoriView u = find(event.getId());
		u.setNote(event.getNote());
		u.setRagioneSociale(event.getRagioneSociale());
		session().update(u);
	}

	@EventListener
	public void apply(FornitoriDeleted event, EventStream<ApiContext> stream) {
		session().delete(find(event.getId()));
	}

}