package com.hequalab.rai.domain.luoghi.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultEvent;
import com.hequalab.rai.domain.luoghi.LuoghiId;

public class LuoghiUpdated extends DefaultEvent<LuoghiId> {

	private static final long serialVersionUID = 1L;
	
	private String indirizzo;
	private String descrizione;
	private String cap;
	private String divisione;
	
	@SuppressWarnings("unused")
	private LuoghiUpdated() {
	}

	public LuoghiUpdated(LuoghiId id, String indirizzo, String descrizione, String cap,String divisione) {
		super(id);
		this.setIndirizzo(indirizzo);
		this.setDescrizione(descrizione);
		this.setCap(cap);
		this.setDivisione(divisione);
	}

	public String getIndirizzo() {
		return indirizzo;
	}
	
	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}
	
	public String getDescrizione() {
		return descrizione;
	}
	
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}
	
	public String getCap() {
		return cap;
	}
	
	public void setCap(String cap) {
		this.cap = cap;
	}

	public String getDivisione() {
		return divisione;
	}

	public void setDivisione(String divisione) {
		this.divisione = divisione;
	}
	
	
}