package com.hequalab.rai.domain.luoghi.events;

/*
 * Class generated by AppWizard
 */

import com.hequalab.rai.dddd.DefaultAggregateDeleted;
import com.hequalab.rai.domain.luoghi.LuoghiId;

public class LuoghiDeleted extends DefaultAggregateDeleted<LuoghiId> {

	private static final long serialVersionUID = 1L;

	
	@SuppressWarnings("unused")
	private LuoghiDeleted() {
	}

	public LuoghiDeleted(LuoghiId id) {
		super(id);
	}				

}