package com.hequalab.rai.domain.lotti;

/*
 * Class generated by AppWizard
 */
 
import com.hequalab.rai.dddd.UUIDIdentity;

public class LottiId extends UUIDIdentity {
	
	private static final long serialVersionUID = 1L;
	
	public LottiId() {
		super();
	}

	public LottiId(String uuid) {
		super(uuid);
	}

}