package com.hequalab.rai.domain.luoghi;

/*
 * Class generated by AppWizard
 */
 
import com.hequalab.rai.dddd.UUIDIdentity;

public class LuoghiId extends UUIDIdentity {
	
	private static final long serialVersionUID = 1L;
	
	public LuoghiId() {
		super();
	}

	public LuoghiId(String uuid) {
		super(uuid);
	}

}